February Community Call Blog
pnp/blog pull request #1067
Opened 2023-02-21 20:30 UTC by preethikakiru

New Article
Blog Post for February Community Call.

2023-02-21 20:30 UTC, preethikakiru commented
Would like to note that I will add three more questions with their respective answers later on.

2023-02-21 23:59 UTC, davidchesnut requested changes

2023-02-21 23:59 UTC, davidchesnut commented on content/office-add-ins-community-call/2023-02-08/index.md
> +summary: "Topics include: Create a spreadsheet from your website by David Chestnut, Upcoming Preview Word APIs by Yun Wang, and Add-in Support for new Outlook by Nikita Mitta and Juan Balmori. The ca
```suggestion
summary: "Topics include: Create a spreadsheet from your website by David Chesnut, Upcoming Preview Word APIs by Yun Wang, and Add-in Support for new Outlook by Nikita Mitta and Juan Balmori. The call was hosted by Preethika Kiruveedula. Recorded on February 8, 2023."
```

2023-02-21 23:59 UTC, davidchesnut commented on content/office-add-ins-community-call/2023-02-08/index.md
> +We have a sample for this at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/Excel.OfflineStorageAddin, however I think they may be looking for more features such as loading whil
```suggestion
We have a sample at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/Excel.OfflineStorageAddin, that shows some techniques for working offline. However, it would be good to know what additional features you may need for your scenario. Please let us know more at https://aka.ms/m365dev-suggestions.
```

2023-02-22 04:11 UTC, lindalu-MSFT requested changes

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +* Share your feedback on how we can provide you with a better Office Add-ins development experience. Join a community panel.
```suggestion
* Share your feedback on how we can provide a better Office Add-ins development experience. Join a community panel. 
```

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +We have a sample at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/Excel.OfflineStorageAddin, that shows some techniques for working offline. However, it would be good to know w
```suggestion
For a sample that shows some techniques for working offline, see [Excel.OfficlenStoreAddin](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/Excel.OfflineStorageAddin) in our samples GitHub repo. However, it would be good to know what additional features you may need for your scenario. Please let us know more at https://aka.ms/m365dev-suggestions.
```

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +We are improving our processes, including adding API releases to the [Microsoft 365 Roadmap (MSRRP)](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=2&filters=). Periodically check this pag
```suggestion
We are improving our processes, including adding API releases to the [Microsoft 365 Roadmap (MSRRP)](https://www.microsoft.com/microsoft-365/roadmap?rtc=2&filters=). Periodically check this page for feature updates.
```

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +Yes, the sample doesn't use auth, but you should set up auth on the Azure function so that it would have the user name. The [Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/)
```suggestion
Yes, the sample doesn't use auth, but we recommend you set up auth on the Azure function so that it has the user name. For information how to set this up, see  the [Azure Functions](https://learn.microsoft.com/azure/azure-functions/) documentation. You can configure the parameters you pass to the function to pass any values you need.
```

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +Yes, the uploadFile function in authPopup.js takes a name parameter. You can use any name you prefer.
```suggestion
Yes, the uploadFile function in authPopup.js takes a name parameter. Use any name you prefer.
```

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +Make sure that the template is referencing the CDN for Office.js. If you need further guidance, [open an issue on GitHub](https://github.com/OfficeDev/office-js/issues/new/choose).
```suggestion
Make sure that the template refers to the CDN for Office.js. If you need further guidance, [open an issue on GitHub](https://github.com/OfficeDev/office-js/issues/new/choose). 
```

2023-02-22 04:11 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +Yes. COM and VSTO add-ins that include VBA will not be supported in the new Outlook on Windows.
```suggestion
Yes. COM and VSTO add-ins include VBA and will not be supported in the new Outlook on Windows.
```

2023-02-22 22:45 UTC, davidchesnut approved these changes
One more change to fix a typo, otherwise looks good!

2023-02-22 22:45 UTC, davidchesnut commented on content/office-add-ins-community-call/2023-02-08/index.md
> +For a sample that shows some techniques for working offline, see [Excel.OfficlenStoreAddin](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/Excel.OfflineStorageAddin) in our samp
```suggestion
For a sample that shows some techniques for working offline, see [Techniques to access data from an Office Add-in when offline](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/Excel.OfflineStorageAddin) in our samples GitHub repo. However, it would be good to know what additional features you may need for your scenario. Please let us know more at https://aka.ms/m365dev-suggestions.
```

2023-03-02 00:17 UTC, lindalu-MSFT approved these changes
I found two formatting errors, that's it!

2023-03-02 00:17 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +*•	Call to Action for Outlook Add-in Mobile Developers – provide feedback on Outlook add-in scenarios you are trying to support [Outlook Mobile Add-in Developer Survey](https://forms.office.com/Pages
```suggestion
* Call to Action for Outlook Add-in Mobile Developers – provide feedback on Outlook add-in scenarios you are trying to support [Outlook Mobile Add-in Developer Survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRw5b9d2wAdRLj9NKAu1xfddUM1pW).
```

2023-03-02 00:17 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-02-08/index.md
> +* Please complete the [Office add-in developing experience survey](https://forms.office.com/r/wmzCgccbPa)
```suggestion
* Please complete the [Office add-in developing experience survey](https://forms.office.com/r/wmzCgccbPa).
```

2023-03-06 18:14 UTC, merged