March Community Call
pnp/blog pull request #1159
Opened 2023-03-23 18:52 UTC by preethikakiru

Blog Post for March 8th Office Add-ins Community Call.

2023-03-23 20:35 UTC, lindalu-MSFT requested changes

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/images/Session-Promo-Mar-2023.jpg
Not a biggie, but this should be "Office Add-ins community call". MSFT style uses sentence case capitalization. For more information, see https://learn.microsoft.com/style-guide/capitalization.

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +summary: "Topic included was: March 2023 Word Extensibility APIs (Preview) presented by Yun Wang, Principal Product Manager at Microsoft. The call was hosted by Preethika Kiruveedula. Recorded on Mar
```suggestion
summary: "Topic: March 2023 Word Extensibility APIs (preview) presented by Yun Wang, Principal Product Manager at Microsoft. The call was hosted by Preethika Kiruveedula. Recorded on March 8, 2023."
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* **Word Extensibility APIs (Preview) - March 2023.** Five Word desktop APIs reviewed in last month’s call plus 3 new features (Application.retrieveStylesFromBase64, recognize deleted content control
```suggestion
* **Word Extensibility APIs (preview) - March 2023.** Five Word desktop APIs reviewed in last month’s call plus three new features (Application.retrieveStylesFromBase64, recognize deleted content controls and plain text content control support), are available now for you to test.  Requires running desktop version 16.0.16130.20218 and above.  Hear about all eight desktop features plus one new Word online feature “Track changes for content controls” is now in production. Targeting mid-year GA on features.
```
In body text, spell out whole numbers from zero through nine.

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* Call to Action for Outlook Add-in Mobile Developers – provide feedback on Outlook add-in scenarios you are trying to support [Outlook Mobile Add-in Developer Survey](https://forms.office.com/Pages/
```suggestion
* Call to action for Outlook add-in mobile developers – provide feedback on Outlook add-in scenarios you're trying to support [Outlook Mobile Add-in Developer Survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRw5b9d2wAdRLj9NKAu1xfddUM1pW).
```
This link doesn't work? https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRw5b9d2wAdRLj9NKAu1xfddUM1pW

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* Join a Community panel – product focused add-in discussion groups
```suggestion
* Join a community panel – product focused add-in discussion groups.
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* •	Follow channels in twitter to see call agendas, important updates, and release announcements.
```suggestion
* Follow channels in Twitter to see call agendas, important updates, and release announcements. 
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* [Next community call ](https://aka.ms/officeaddinscommunitycall) on April 12th at 8:00 AM Pacific Time.
```suggestion
* [Next community call](https://aka.ms/officeaddinscommunitycall) on April 12th at 8:00 AM Pacific Time.
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +**How long does it take to reflect the changes made in app registration inside azure portal to the development?**
```suggestion
**How long does it take to reflect the changes made in app registration inside Azure portal to the development?**
```
Don't forget to add the answer or delete!

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +**What's the timeframe for providing feedback from the "Auto install and auto launch add-ins for Word, Excel and PowerPoint" survey?**
```suggestion
**What's the timeframe for providing feedback from the "Auto install and auto launch add-ins for Word, Excel, and PowerPoint" survey?**
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +Thank you for sharing great feedback. We are planning to present the survey results in the next community call.
```suggestion
Thank you for sharing great feedback. We're planning to present the survey results in the next community call.
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +1. We already have the events you need. The way we recommend handling this is case is the following:
```suggestion
1. We already have the events you need. We recommend you use Event-based add-ins and subscribe the OnCompose events in the following manner.
```
Use a "procedure like" answer for clarity and accessibility. Please double check I haven't changed any meaning!

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +  Using Event based add-ins and subscribe the OnCOmpose events. This will trigger an event you can handle when folks create new messages or reply/reply all/fwd. As part of the handler of that event y
```suggestion
   * Trigger an event you can handle when users create new messages, reply, reply all, or forward. 
   * As part of the handler of that event, display a notification bar so the user can select from the predefined list of subjects.  
   * When the notification bar is clicked, you can open a task pane from which the user can select and insert. 
   * To make sure that the user is actually changing the subject, add an OnSend event handler. After the user clicks “send” you can validate if the subject is compliant and stop the send until the user changes it.
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +2. The ability to support on-send Outlook events (or Smart Alerts) in iPhone or Android. This is in our backlog and  been currently planned for implementation. 
```suggestion
2. Regarding the ability to support on-send Outlook events (or Smart Alerts) in iPhone or Android, this is in our backlog and is planned for implementation. 
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* Quick Starts: [Outlook](https://docs.microsoft.com/office/dev/add-ins/quickstarts/outlook-quickstart), [Excel](https://docs.microsoft.com/office/dev/add-ins/quickstarts/excel-quickstart-jquery), [W
```suggestion
* Quick Starts: 
  * [Outlook](https://learn.microsoft.com/office/dev/add-ins/quickstarts/outlook-quickstart)
  * [Excel](https://learn.microsoft.com/office/dev/add-ins/quickstarts/excel-quickstart-jquery)
  * [Word](https://learn.microsoft.com/office/dev/add-ins/quickstarts/word-quickstart)
  * [PowerPoint](https://learn.microsoft.com/office/dev/add-ins/quickstarts/powerpoint-quickstart)
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* Community panels – discussion and feedback
```suggestion
* Community panels – discussion and feedback:
```

2023-03-23 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2023-03-08/index.md
> +* See the full blog post for this call in the Microsoft 365 platform community blog [https://aka.ms/m365pnp/blog](https://aka.ms/m365pnp/blog)
```suggestion
* See the full blog post for this call in the [Microsoft 365 platform community blog](https://aka.ms/m365pnp/blog)
```

2023-03-24 15:55 UTC, davidchesnut commented on content/office-add-ins-community-call/2023-03-08/index.md
> +We don't have any plans to support this in the near future.
Is there a request for this on the feature request site? Perhaps we should ask them to upvote there.

2023-03-30 23:06 UTC, merged