Adds release announcement post for CLI for Microsoft 365 v6.7
pnp/blog pull request #1266
Opened 2023-04-26 14:00 UTC by martinlingstuyl

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request
Release announcement post for CLI for Microsoft 365 v6.7

2023-04-26 14:00 UTC, martinlingstuyl commented
I've put it in draft, the release will be tuesday 2nd of May

2023-04-26 14:59 UTC, Jwaegebaert requested changes
Awesome work @martinlingstuyl!!

I've left a few pointers you can look at 😄

2023-04-26 14:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/images/mendable-preview.png
This image can be removed

2023-04-26 14:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform commandline tool. It helps you manage your Microsoft 365 tenant and SharePoint Framework projects. No matter which operating syste
```suggestion
[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool. It helps you manage your Microsoft 365 tenant and SharePoint Framework projects. No matter which operating system or shell you use.
```

2023-04-26 14:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +
Two empty lines instead of one 😄 

```suggestion

```

2023-04-26 14:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +If you have any ideas or suggestions for new commands, please let us know by creating a [new issue](https://github.com/pnp/cli-microsoft365/issues/new?assignees=&labels=&template=new-command.yml&titl
It could be nice to add little tease here to the 🌶️ project

2023-04-26 14:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Changelog v6.7.0](https://pnp.github.io/cli-microsoft365/about/release-notes/#v670)
Another big change imo in v6.7 is the prompt for option sets that's definitely worth mentioning in the post. Maybe we could even add a gif here that shows this change in action.

2023-04-26 14:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
Adam, [Nicolas](https://github.com/nickscamara) are missing here and I guess me too 😅

2023-04-26 15:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
How are you getting these? I'm just checking the assigned-to fields of the accompanied PR's..

2023-04-26 15:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Changelog v6.7.0](https://pnp.github.io/cli-microsoft365/about/release-notes/#v670)
Good point!

2023-04-26 15:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +If you have any ideas or suggestions for new commands, please let us know by creating a [new issue](https://github.com/pnp/cli-microsoft365/issues/new?assignees=&labels=&template=new-command.yml&titl
Indeed! I will..

2023-04-26 15:33 UTC, milanholemans requested changes
Nice work @martinlingstuyl! Few small comments.

2023-04-26 15:33 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +type: popular
We should update the type of the previous post to `regular`.

2023-04-26 15:33 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +Working with the recycle bin programmatically has become easier as well. You can now clear a site recycle bin with a simple one liner.
```suggestion
Working with the recycle bin programmatically has become easier as well. You can now clear a site recycle bin with a simple one-liner.
```

2023-04-26 15:33 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +m365 aad user set --userPrincipalName steve@contoso.onmicrosoft.com --firstName John --lastName Doe --jobTitle "Sales Manager" --companyName Contoso --department Sales --officeLocation "New York"
Looks a bit odd that __steve__@contoso.com has first name `John` and last name `Doe` 😄

2023-04-26 15:33 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +
Could we also add an extra example on how to set the manager of the user?

2023-04-26 15:41 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
@martinlingstuyl `git log --format="%an" --after 2023-04-14 | sort -u` works for me

2023-04-26 15:42 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
Nice!!

2023-04-26 17:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
Well, my method isn't anything fancy 😅 

I just look through all the commits on GitHub and look at the authors.

![afbeelding](https://user-images.githubusercontent.com/38426621/234663120-e88fd3d8-1656-4676-96c5-d52d1001efbf.png)

2023-04-26 20:26 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
Even that is simpler than opening the PR's 😅

2023-04-27 10:35 UTC, LuiseFreese commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +type: popular
please downgrade this post to `regular` when you publish v6-7 post: 

https://github.com/pnp/blog/blob/main/content/post/Teams-toolkit-cloudskills-challenge/index.md

2023-05-02 09:20 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Nicolas Scamara](https://github.com/nickscamara)
The last name is incorrect. It should be Camara

2023-05-02 09:24 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +In the previous release, we introduced a chat-based search tool, powered by Mendable, to make it easier to find out how you can achieve your aims using the CLI for Microsoft 365. But we are not stopp
```suggestion
In the previous release, we introduced a chat-based search tool, powered by Mendable, to make it easier to find out how you can achieve your aims using the CLI for Microsoft 365. But we are not stopping there. We're currently in the process of integrating this same chat-based experience into the CLI itself! You will be able to ask your questions to this new CLI assistant without even leaving your terminal! The assistant will search the documentation for you and explain how you can achieve your scenario, it will also list links to the sources where it found what it's saying, for a seamless switch to the CLI for Microsoft 365 website in the browser.
```

2023-05-02 09:31 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Nanddeep Nachan](https://github.com/nanddeepn)
We're missing Jasey here.

2023-05-02 10:03 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-7/index.md
> +- [Nanddeep Nachan](https://github.com/nanddeepn)
Sorry @Jwaegebaert

2023-05-02 12:43 UTC, waldekmastykarz approved these changes

2023-05-02 12:46 UTC, merged