Adds release announcement post CLI for Microsoft 365 v6.8
pnp/blog pull request #1344
Opened 2023-05-26 15:07 UTC by martinlingstuyl

## Category

- [ ] Content fix
- [x] New article

## Related issues
none

## Contents of the Pull Request

Release announcement post CLI for Microsoft 365 v6.8

2023-05-26 18:30 UTC, Jwaegebaert requested changes
Hey @martinlingstuyl, great job on the blog! I've made some suggestions for spelling errors and places where the sentences were a bit difficult to read. 

In my opinion, the section about the docs was a bit brief, but maybe it's better that way so it stays clear. By the way, I'm also thinking of writing a more detailed blog post about why we switched our engine and the steps we had to go through. So if folks want to know more, they can read that 😄

2023-05-26 18:30 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Some people use the CLI for Microsoft 365 interactively. Other people use it to build scripts that can run automomously. The new `m365 setup` command is a wizard-style command that helps you configur
```suggestion
Some people use the CLI for Microsoft 365 interactively. Other people use it to build scripts that can run autonomously. The new `m365 setup` command is a wizard-style command that helps you configure the CLI for Microsoft 365 for your needs. It will ask you a series of questions and based on your answers, it will configure the CLI for Microsoft 365 for you. It also has a few flags to quickly configure the CLI according to some presets based on best practices.
```

2023-05-26 18:30 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +You could already update user information for Azure AD users. In the previous release we added a lot of well-known options, like job title and office location. We've now extended this to any property
```suggestion
You could already update user information for Azure AD users. In the previous release, we added a lot of well-known options, like job title and office location. We've now extended this to any property, even if it's unknown to the CLI for Microsoft 365.
```

2023-05-26 18:30 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Updating our website was a thing we wanted to do for quite some time now. We've swapped to using a new static site generator: Docusaurus. It's been a major thing in terms of development time and disc
```suggestion
Updating our website was a thing we wanted to do for quite some time now. We've swapped to using a new static site generator: Docusaurus. It's been a major thing in terms of development time and discussions internally. But if we've done our job well, the changes should be minimal. 🤞 Of course, you may notice some styling changes... 😊some things have shifted slightly. We also temporarily dropped the search bar. (We'll get it back in due time!) But in the meantime, we fortunately have our AI assistant, so you can still search for answers to your questions.
```

2023-05-26 18:36 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool. It helps you manage your Microsoft 365 tenant and SharePoint Framework projects. No matter which operating syst
```suggestion
[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool. It helps you manage your Microsoft 365 tenant and SharePoint Framework projects. No matter which operating system or shell you use. This release is again brimming with new features and enhancements. We've added no less than **18 new commands** for managing multiple Microsoft 365 services. We've also added **40+ enhancements** to existing commands. This is also the release in which we added 🌶️ chili, our AI-based docs assistant and built an entire new site for the CLI for Microsoft 365. Interested? Read on for more details.
```

2023-05-26 18:36 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +m365 spo term set list --termGroupName "DMS" --webUrl https://contoso.sharepoint.com/sites/project-x
```suggestion
m365 spo term set list --termGroupName "DMS" --webUrl "https://contoso.sharepoint.com/sites/project-x"
```

2023-05-26 18:36 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +You could already update user information for Azure AD users. In the previous release we added a lot of well-known options, like job title and office location. We've now extended this to any property
```suggestion
You could already update user information for Azure AD users. In the previous release we added a lot of well-known options, like 'job title' and 'office location'. We've now extended this to any property, even if it's unknown to the CLI for Microsoft 365.
```

2023-05-26 18:38 UTC, martinlingstuyl commented
> In my opinion, the section about the docs was a bit brief

I had thought of asking you to write it yourself as I had expected this. 😆😆 perfectly fine though if you share (y)our learnings in a separate post. I agree with you that that is probably better.

2023-05-26 18:42 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +We've shipped several enhancements that are very useful when working the SharePoint Term Store. You no longer need to be a SharePoint administrator to manage the term store. If you only have permissi
on-site is not what I meant though...

We can change it to `site-level term store`

2023-05-26 18:44 UTC, martinlingstuyl commented
But feel free to add something @Jwaegebaert ☺️

2023-05-26 19:22 UTC, milanholemans requested changes
Hi @martinlingstuyl great job! I made a few suggestions (just noticed Jasey also did a review so might have some duplicates).

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +We've added more commands for working with SharePoint. We've made it easier to manage Application Customizers, ListView Command Sets and items in the recycle bin. You can also update large amounts of
```suggestion
We've added more commands for working with SharePoint. We've made it easier to manage Application Customizers, ListView Command Sets, and items in the recycle bin. You can also update large amounts of list items.
```

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +m365 spo tenant commandset  set --id 3  --clientSideComponentProperties '{ "someProperty": "Some value" }'
```suggestion
m365 spo tenant commandset set --id 3  --clientSideComponentProperties '{ "someProperty": "Some value" }'
```

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +To update a lot of items as quick as possible, run:
```suggestion
To update a lot of items as quickly as possible, run:
```

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Remove an item from first-stage recycle bin:
This command is capable of removing items in both first stage and second-stage recycle bins.

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +We've shipped several enhancements that are very useful when working the SharePoint Term Store. You no longer need to be a SharePoint administrator to manage the term store. If you only have permissi
```suggestion
We've shipped several enhancements that are very useful when working with the SharePoint Term Store. You no longer need to be a SharePoint administrator to manage the term store. If you only have permissions as a term store administrator, you can manage terms, term sets, and term groups in the global term store using the CLI for Microsoft 365. Aside from the global term store, you can now also manage term stores on-site collections. For both scenarios you'll need to use the new `--webUrl` option that's added to every command. The CLI for Microsoft 365 will now connect to the global or local term store, using the site you've specified. 
```

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +You could already update user information for Azure AD users. In the previous release we added a lot of well-known options, like job title and office location. We've now extended this to any property
```suggestion
You could already update user information for Azure AD users. In the previous release, we added a lot of well-known options, like job titles and office locations. We've now extended this to any property, even if it's unknown to the CLI for Microsoft 365.
```

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Updating our website was a thing we wanted to do for quite some time now. We've swapped to using a new static site generator: Docusaurus. It's been a major thing in terms of development time and disc
```suggestion
Updating our website was a thing we wanted to do for quite some time now. We've swapped to using a new static site generator: Docusaurus. It's been a major thing in terms of development time and discussions internally. But if we've done our job well, the changes should be minimal. 🤞 Of course, you may notice some styling changes... 😊some things have shifted slightly. We also temporarily dropped the search bar. (We'll get it back in due time!) But in the meantime, we fortunately have our AI-assistant, so you can still search for answers to your questions.
```

2023-05-26 19:22 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +
Aren't we missing [dojcsakj](https://github.com/dojcsakj)?
https://github.com/pnp/cli-microsoft365/issues/4865

2023-05-27 14:16 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Remove an item from first-stage recycle bin:
So what do you mean @milanholemans? You'd like an extra example for the second-stage scenario?

2023-05-27 14:18 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Remove an item from first-stage recycle bin:
No just the description. Right now you are saying that this command can remove first-stage recycle bin items. But it can remove both first stage and second stage recycle bin items.

2023-05-27 14:18 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +
I haven't yet updated these lists... ran out of time :-)

2023-05-27 14:21 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +Remove an item from first-stage recycle bin:
ah, I see 😊

2023-05-31 07:09 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +
@milanholemans, do you remember what the decision was about the high fives? Do we list everyone? or exclude maintainers and contributors?

2023-05-31 07:11 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +
As far as I know, we exclude maintainers and contributors.

2023-05-31 07:49 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/index.md
> +
That seems wise. I'll update it :-)

2023-05-31 09:42 UTC, waldekmastykarz approved these changes

2023-05-31 09:52 UTC, merged