Added 'CLI for Microsoft 365 v6.9' release announcement
pnp/blog pull request #1415
Opened 2023-06-27 21:01 UTC by Jwaegebaert

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

This PR is the release announcement for the v6.9 release of the CLI for Microsoft 365.

2023-06-28 11:52 UTC, martinlingstuyl requested changes
Hi @Jwaegebaert, great work! Do check out my comments 👇

2023-06-28 11:52 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +### Introducing our New Website with Docusaurus 🦖
Did we not already mention this in the previous release?

2023-06-28 11:52 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +With the foundational groundwork already laid by refactoring the core aspects of our commands, we are now diligently removing all remaining promises to achieve a fully async/await codebase. This meti
We're not really removing promises. Async/await is also promises.

2023-06-28 11:52 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +Our CLI for Microsoft 365 now features **8 impressive new commands**, giving you unrivaled control over various Microsoft 365 services. From SharePoint Application Customizers to sensitivity labels a
On a general note, I think we may want to be a little less hyperbolic. (not only in this paragraph) The problem with using hyperboles a lot, is that they are subject to inflation: the value of a hyperbole decreases if you use them all the time. In other words: It becomes harder to let things jump out if you truly want them to jump out.

2023-06-28 11:52 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +We're excited to unveil a major undertaking that has consumed our efforts for quite some time: the comprehensive refactoring of our codebase to embrace the asynchronous programming model using **asyn
This change is really a refactoring: it doesn't offer real value to the end-user. I'd suggest that we move it down below the things that do impact the user directly, and maybe make it a bit shorter as well.

It also doesn't really benefit the performance and reliability of our commands. 

Instead of trying to find benefits for the end-user: I think I'd not focus on that, but rather on the community-aspect that this displays: This refactoring DOES show the power of community and the value of 'sharing is caring', because this has been a lot of work that has been done in a short time.

2023-06-28 11:52 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +Our dedication to enhancing our capabilities knows no bounds. We've poured our heart and soul into this release, and the results are truly remarkable.
Another exquisite example of beautifully crafted hyperbolic language bordering on the divine. 😁

2023-06-29 07:28 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +### Introducing our New Website with Docusaurus 🦖
Yep, it's true! When you check out the changelog, you'll see that it's included in this latest release, along with the enhanced `Algolia` search mentioned in the section. Since it's a significant update and I'm interested in hearing what people think about it, I brought it up again.

2023-06-29 07:31 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +### Introducing our New Website with Docusaurus 🦖
Yeah, now I remember: we released it in the beta right after releasing the major version, and mentioned it in the announcement post.

2023-06-29 20:29 UTC, Jwaegebaert commented
Thanks for the review @martinlingstuyl ❤️ 

All fair pointers and a good suggestion to dial a bit back on the overly extensive hyperbolic language usage 😅

2023-06-30 09:04 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md
> +### Embracing the Power of async/await in our Codebase
Much better!! ⚡

Still: I'd move it down below the 'Filter Flows' section. As that has immediate benefits for the user.

2023-06-30 12:09 UTC, merged