Adds CLI for Microsoft 365 v6.10 release blog post
pnp/blog pull request #1466
Opened 2023-07-29 01:29 UTC by Adam-it

## Category

- [X] New article

## Contents of the Pull Request

Adds the CLI for Microsoft 365 release notes for this month. 

👉 Should be merged together with the CLI v6.10 release

2023-07-30 12:04 UTC, Jwaegebaert requested changes
Awesome work @Adam-it with the release post. Very well written! 

I've left a few comments you can take a look at.

2023-07-30 12:04 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Aadit Ambadkar](https://github.com/Aadit-Ambadkar)
Looking at the script from Milan to validate the High Fives there isn't anybody that should be mentioned here.

![image](https://github.com/pnp/blog/assets/38426621/bc25c731-f877-42cc-90ee-aa9480ece861)

2023-07-30 19:12 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +  - Azure AD
good point

2023-07-30 19:24 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
@Jwaegebaert why https://github.com/dojcsakj should be on that list?
both of his PR's were closed before this month 
![image](https://github.com/pnp/blog/assets/58668583/846fc02f-6c21-4787-aa4e-9c7de32b8428)
and he was already mentioned in the previous month.
Am I missing something here?

2023-07-30 19:25 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
@Jwaegebaert same story for [manan-m-shah](https://github.com/manan-m-shah)
closed in june 
![image](https://github.com/pnp/blog/assets/58668583/bf741646-ed58-4cec-8b7a-080f44d9e7c4)
single PR

2023-07-30 20:01 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Aadit Ambadkar](https://github.com/Aadit-Ambadkar)
Wow I did not know there is a script for that 🙂.
Anyway I added him because of this issue 
https://github.com/pnp/cli-microsoft365/issues/4898 
I know it was some time ago but it was actually now when this idea came to life and PR was closed. Without that feedback we would not add this command

2023-07-30 20:03 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +  - Azure AD
✅

2023-07-30 20:03 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [m365 aad sp list](https://pnp.github.io/cli-microsoft365/cmd/aad/sp/sp-list/)
✅

2023-07-30 20:03 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +To lists all permissions of a Power Apps app simply run:
✅

2023-07-30 20:03 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +In order to set a new owner for a Power Apps app and remove the previous owner, all you need to do is:
✅

2023-07-30 20:03 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +### Power Apps Management
✅

2023-07-30 20:04 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
I did not do that. @Jwaegebaert  please go over the above comments to check why

2023-07-30 20:04 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Aadit Ambadkar](https://github.com/Aadit-Ambadkar)
I did not do that. @Jwaegebaert  please go over the above comments to check why

2023-07-30 20:04 UTC, Adam-it commented
@Jwaegebaert thanks for your review. I did most of the stuff and IMO it's ready to be merged when the release is out. 
Two things I left open so maybe we could recheck them together.

2023-07-30 23:15 UTC, milanholemans requested changes
Great job writing this release post @Adam-it 👏
I left some small comments. Other than that, looks great!

Not a single emoji, my 🧠 is 🤯!

2023-07-30 23:15 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Smita Nachan](https://github.com/SmitaNachan)
Seems like Smita didn't contribute this release.

2023-07-30 23:15 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Aadit Ambadkar](https://github.com/Aadit-Ambadkar)
We only take the creation dates of issues into account. This is because it's possible that issues stay open for months/years and we want to acknowledge our gratitude at the time of creation, and not after few months/years 😊.
This issue was created in May, so he was mentioned in that release: https://pnp.github.io/blog/cli-for-microsoft-365/cli-for-microsoft-365-v6-8/#high-fives

2023-07-31 09:13 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Smita Nachan](https://github.com/SmitaNachan)
```suggestion
- [Saurabh Tripathi](https://github.com/Saurabh7019)
```

2023-07-31 09:14 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +## Get Started Today!
```suggestion
We express our deepest gratitude for the time and effort you have invested in CLI for Microsoft 365, improving its progress and enriching its capabilities. Your contributions have played a significant role in advancing this project and empowering users worldwide. Thank you for your commitment and valuable assistance!

## Get Started Today!
```

2023-07-31 09:16 UTC, closed without merging

2023-07-31 09:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
Sorry about that one, I looked at the wrong month 😅