Adds a new CLI for Microsoft 365 release blog post
pnp/blog pull request #1513
Opened 2023-08-28 22:17 UTC by Adam-it

## Category

- [X] New article

## Contents of the Pull Request

Adds a new CLI for Microsoft 365 release blog post.

2023-08-29 07:49 UTC, waldekmastykarz requested changes
Very nice! A few cosmetic changes that I'd suggest

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +### SharePoint Framework Projects v1.18.0-beta.5 Support
```suggestion
### SharePoint Framework Projects v1.18.0-beta.5 support
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +### Extended SPO file copy command
```suggestion
### Extended the 'spo file copy' command
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +In this release, we also improved the `spo file copy` command with two new options. One of them is definitely worth checking as it allows to clear the author and created date. Check out the [related
Let's expand what these options are and include some examples

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +### The fun never stops, improving our Codebase
```suggestion
### The fun never stops, improving our codebase
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +Not so long ago we migrated our docs to a new fresh framework adding a couple of awesome features along the way like AI search powered by [Mendable](https://www.mendable.ai/). In this release, we wor
```suggestion
Not so long ago we migrated our docs to a new static site generator adding a couple of awesome features along the way like AI search powered by [Mendable](https://www.mendable.ai/). In this release, we worked on adding more valuable content and added a new section with contributing guidance to the CLI for Microsoft 365. How to add a new command? How to add unit tests? How to add a new script sample? All that and much much more will become super clear after [checking out our docs](https://pnp.github.io/cli-microsoft365/contribute/contributing-guide).
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +In this minor release, we continue our work on refactoring the code base to embrace the asynchronous programming model using **async/await**. All this would not have been possible without our awesome
```suggestion
In this minor release, we continued our work on refactoring the code base to embrace the asynchronous programming model using **async/await**. All this would not have been possible without our awesome contributors and their dedication to CLI for Microsoft 365. Just have a look at the [list](https://github.com/pnp/cli-microsoft365/issues/3618) to get a feeling of the amount of work already done and what is left.
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +### Power Apps Management
```suggestion
### Power Apps management
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +> Explore the [release notes](https://aka.ms/cli-m365/notes) to discover an array of exciting features and improvements that will revolutionize your Microsoft 365 journey.
I suggest that we link specifically to v6.11 release notes to help readers stay in the context of this post, also in the future when we add newer versions to release notes

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +## Upcoming Changes
```suggestion
## Upcoming changes
```

2023-08-29 07:49 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +### Expanding Command Arsenal
```suggestion
### Expanding command arsenal
```

2023-08-30 19:55 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +> Explore the [release notes](https://aka.ms/cli-m365/notes) to discover an array of exciting features and improvements that will revolutionize your Microsoft 365 journey.
```suggestion
> Explore the [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes#v6110) to discover an array of exciting features and improvements that will revolutionize your Microsoft 365 journey.
```

2023-08-30 20:34 UTC, milanholemans requested changes
Awesome work @Adam-it 👏 
In the comments you can find the stuff I would change 😊

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +For example to add a co-owner permissions for a security group to a Power Apps app simply run:
```suggestion
For example to add co-owner permissions for a security group to a Power Apps app simply run:
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +In the last release we introduced a couple of new commands that allowed you to manage Power Apps and we are not slowing down. In this release, we added two more commands to give you more control over
```suggestion
In the last release we introduced a couple of new commands that allowed you to manage Power Apps apps and we are not slowing down. In this release, we added two more commands to give you more control over permission management.
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +Or to share a Power Apps app with everyone in the tenant type:
```suggestion
Or to share a Power Apps app with everyone in the tenant, use:
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +Thanks to that you may for example remove permissions of a specific user for a specific app by simply:
```suggestion
Thanks to that, you may for example remove permissions of a specific user for a specific app by running:
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +You may configure CLI for Microsoft 365 to meet your personal preferences. Thanks to that you may for example configure how CLI should behave in case a URL is returned or what should be the default o
```suggestion
You may configure CLI for Microsoft 365 to meet your personal preferences. Thanks to that you may, for example, configure how CLI should behave in case a URL is returned or what should be the default output mode, or configure CLI to prompt for missing values in required options, or so much much more that if you haven't, you should definitely [give it a check](https://pnp.github.io/cli-microsoft365/user-guide/configuring-cli). In this release, we added a command that allows you to have a quick overview of all self-set configurations.
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +I will be honest this is one of my personal favorites. Who wouldn't want some kind of flow that will automagically build, package, and deploy your solution after adding a new feature to your code bas
```suggestion
I will be honest, this is one of our personal favorites. Who wouldn't want some kind of flow that will automatically build, package, and deploy your solution after adding a new feature to your code base? In the IT world, we use workflows (pipelines) for exactly that. We added a new command that will generate a YAML GitHub workflow for a given SPFx project, giving you a huge head start in creating a good quality CI/CD flow. Let's check out what's possible.
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +To add a GitHub workflow for a SharePoint Framework project with an application login method triggered on push to main you only need to run:
```suggestion
To add a GitHub workflow for a SharePoint Framework project that uses an application login and triggers for every push to the `main` branch, you should run:
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +And if you want to have a CI/CD pipeline to deploy your app to a Site level app catalog just run:
```suggestion
And if you want to have a CI/CD pipeline to deploy your app to a site level app catalog just run:
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +Not so long ago we migrated our docs to a new static site generator adding a couple of awesome features along the way like AI search powered by [Mendable](https://www.mendable.ai/). In this release,
```suggestion
Not so long ago we migrated our docs to a new static site generator adding a couple of awesome features along the way like AI search powered by [Mendable](https://www.mendable.ai/). In this release, we worked on adding more valuable content and added a new section with contributing guidance to the CLI for Microsoft 365. How to add a new command? How to add unit tests? How to add a new script sample? All that and much much more will become super clear after checking out our [contribute section](https://pnp.github.io/cli-microsoft365/contribute/contributing-guide).
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +## Contributors
Let's also not forget our high fives:

```
- [alpozz](https://github.com/alpozz)
- [Albert-Jan Schot](https://github.com/appieschot)
- [Brian Frick](https://github.com/frick-brian)
- [Ganesh Sanap](https://github.com/ganesh-sanap)
- [Garry Trinder](https://github.com/garrytrinder)
- [Stefan Rauchegger](https://github.com/smadep)
```

2023-08-30 20:34 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +We value your feedback and are eager to hear from you. If you have any suggestions for improvement or want to engage with our community, you can reach out to us on [GitHub](https://github.com/pnp/cli
RIP Twitter 😄

2023-08-31 09:33 UTC, waldekmastykarz approved these changes

2023-08-31 09:33 UTC, merged