Adds the release announcement post for v7 of the CLI for Microsoft 365
pnp/blog pull request #1572
Opened 2023-09-27 20:25 UTC by martinlingstuyl

## Category

- [ ] Content fix
- [x] New article

## Related issues

none

## Contents of the Pull Request

Adds the release announcement post for v7 of the CLI for Microsoft 365

2023-09-28 10:47 UTC, LuiseFreese commented
@martinlingstuyl do you need me to help here or would you like to publish this on your own?

2023-09-28 10:48 UTC, martinlingstuyl commented
> @martinlingstuyl do you need me to help here or would you like to publish this on your own?

I'm still waiting on a review by the maintainers team...

2023-09-28 10:48 UTC, martinlingstuyl commented
I'll probably ask waldek to publish it, so never mind. Thanks for asking though!

2023-09-28 10:51 UTC, LuiseFreese commented
[heart]         Luise Freese reacted to your message:
________________________________
From: Martin Lingstuyl ***@***.***>
Sent: Thursday, September 28, 2023 10:48:42 AM
To: pnp/blog ***@***.***>
Cc: Luise Freese ***@***.***>; Comment ***@***.***>
Subject: Re: [pnp/blog] Adds the release announcement post for v7 of the CLI for Microsoft 365 (PR #1572)


I'll probably ask waldek to publish it, so never mind. Thanks for asking though!

—
Reply to this email directly, view it on GitHub<https://github.com/pnp/blog/pull/1572#issuecomment-1738912413>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AL5FMIQZQFQENXOFUMSBX4TX4VIYVANCNFSM6AAAAAA5J5LUGQ>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-09-28 15:09 UTC, Jwaegebaert requested changes
Nice work with the post @martinlingstuyl. I've left a few pointers you can take a look at.

2023-09-28 15:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/images/banner-cli-m365.png
Let's update the image so it includes the v7 upgrade guidance

![banner-cli-m365-28-09-23](https://github.com/pnp/blog/assets/38426621/bfac2301-ffd6-4954-8ae7-d3e8020db71d)

2023-09-28 15:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +date: 2023-09-28T06:00:00.000Z
Shouldn't this be the date when we officially release `v7`?

2023-09-28 23:07 UTC, Adam-it approved these changes
Awesome work 👏.
I added some tiny comments

2023-09-28 23:07 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +#### Even more commands...
no sure. This chapter seems a bit incomplete 😅. I would either remove it or add a bit more light and info and maybe links to issues or developed commands

2023-09-28 23:07 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +- [[János Dojcsák](https://github.com/dojcsakj)](https://github.com/dojcsakj)
```suggestion
- [János Dojcsák](https://github.com/dojcsakj)](https://github.com/dojcsakj)
```

is this second [ in `[[János...` needed?

2023-09-29 21:17 UTC, milanholemans requested changes
Nicely done @martinlingstuyl!
Left a few comments while reading this cool blog post.

2023-09-29 21:17 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command line tool based on Node.js that helps you manage many things around Microsoft 365 and your SPFx project. You may manage On
In fact, `tonne` is right here 🙂 unless we write in the imperial system 😄 

https://grammarist.com/spelling/ton-tonne/

> If you’re in the United States or another country that uses the imperial system, you should use the word “ton” when measuring weight or mass.
If you’re in the United Kingdom or another country that uses the metric system, you should use the word “tonne.”


```suggestion
[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command line tool based on Node.js that helps you manage many things around Microsoft 365 and your SPFx project. You may manage OneDrive, Planner, Power Apps and Automate, Teams, Viva Engage (Yammer), SharePoint (of course), and many many more. The list keeps on growing and growing. In this minor release, we introduced new commands as well as a tonne of improvements.
```

2023-09-29 21:17 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +To learn more about managing list item attachments, see the [list item attachment commands](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-attachment-list) in our docs.
Instead of this, I'd include some bullet points with a hyperlink to every command

- [Command A](https://github.com)
- [Command B](https://github.com)
- [Command C](https://github.com)

2023-09-29 21:17 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +To learn more about managing Entra ID Groups, see the [aad group commands](https://pnp.github.io/cli-microsoft365/cmd/aad/group/group-remove) in our docs.
Also here it would be more useful to just list the commands. This means that the reader has to do a lot less effort to look which other commands are available.

2023-09-29 21:17 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +- [János Dojcsák](https://github.com/dojcsakj)](https://github.com/dojcsakj)
```suggestion
- [János Dojcsák](https://github.com/dojcsakj)
```

2023-09-29 21:17 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +What else could we simplify? Let us know what you think by helping out with one of our [open issues](https://github.com/pnp/cli-microsoft365/issues) or chime in on our [discussions](https://github.co
Maybe we should reference Discord instead of GH discussions?

2023-09-29 22:15 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-11/index.md
> +[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command line tool based on Node.js that helps you manage many things around Microsoft 365 and your SPFx project. You may manage On
Then apparently I'm US-focused. 😂 a tonne of changes feels wrong.

2023-10-02 07:27 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +What else could we simplify? Let us know what you think by helping out with one of our [open issues](https://github.com/pnp/cli-microsoft365/issues) or chime in on our [discussions](https://github.co
I've reversed the order...

2023-10-02 07:37 UTC, Jwaegebaert approved these changes
Noticed two minor details, but besides those, looks good to me! Awesome job!

2023-10-02 07:37 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +date: 2023-09-30T06:00:00.000Z
Let's not forget to update the date 😉

2023-10-02 07:37 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/index.md
> +A warm welcome to this month's new contributors! (in alphabetical order):
```suggestion
A warm welcome to this month's new contributor!:
```

2023-10-02 10:31 UTC, merged