Added 'CLI for Microsoft 365 v7.1' release announcement
pnp/blog pull request #1628
Opened 2023-10-28 07:37 UTC by Jwaegebaert

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

This PR is the release announcement for the v7.1 release of the CLI for Microsoft 365.

2023-10-30 11:09 UTC, martinlingstuyl reviewed
Looks fine @Jwaegebaert! One minor detail that I ran into.

2023-10-30 11:09 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-1/index.md
> +type: regular
```suggestion
type: popular
```

2023-10-30 19:47 UTC, milanholemans requested changes
Nice post @Jwaegebaert!
Just one small addition to be future proof 🙂

2023-10-30 19:47 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-1/index.md
> +We value your feedback and are eager to hear from you. If you have any suggestions for improvement or want to engage with our community, you can reach out to us on [GitHub](https://github.com/pnp/cli
```suggestion
We value your feedback and are eager to hear from you. If you have any suggestions for improvement or want to engage with our community, you can reach out to us on [GitHub](https://github.com/pnp/cli-microsoft365/issues), [Discord](https://aka.ms/cli-m365/discord), or [X](https://x.com/climicrosoft365). Don't hesitate to connect with us. Your input plays a vital role in shaping the future of CLI for Microsoft 365.
```

2023-10-31 10:14 UTC, Jwaegebaert commented
Thanks @milanholemans and @martinlingstuyl for the review!

2023-10-31 10:47 UTC, merged