Cli for Microsoft 365 release v7.2 blog post
pnp/blog pull request #1651
Opened 2023-11-27 00:25 UTC by Adam-it

## Category

- [x] New article

2023-11-27 07:31 UTC, waldekmastykarz requested changes
Awesome!

2023-11-27 07:31 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsoft 365 tenant and SharePoint Framework projects. This minor release introd
```suggestion
[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsoft 365 tenant and SharePoint Framework projects. This minor release introduces a number of new administrative commands as well as a ton of awesome improvements.
```

2023-11-27 07:31 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +### Azure Active Directory
Since we refer to AAD as Microsoft Entra in the paragraph below, shall we rename this heading to Microsoft Entra ID?

2023-11-27 07:31 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +- //TODO
😱

2023-11-27 07:34 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +### Azure Active Directory
Good point.

2023-11-27 07:35 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +- //TODO
Yep, I will run the script to generate this today. I didn't know where to find it

2023-11-27 20:47 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +### Azure Active Directory
```suggestion
### Microsoft Entra
```

2023-11-27 20:57 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +- //TODO
```suggestion
- [brugh](https://github.com/brugh)
- [sergey-ovsiannikov](https://github.com/sergey-ovsiannikov)
- [David Barratt](https://github.com/davidbarratt)
- [Garry Trinder](https://github.com/garrytrinder)
- [Gustavo Velez](https://github.com/gavdgavd)
- [Jacky Lam](https://github.com/jackylamhk)
- [Paul](https://github.com/paul-gladoon)
```

2023-11-27 23:37 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
> +[CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsoft 365 tenant and SharePoint Framework projects. This minor release introd
This is debatable 😀
A ton is 2000 pounds (imperial system)
A tonne is 1000 kilograms (metric system)

I'm more in favor for the metric one since it's used in 99% of the world.

2023-11-27 23:48 UTC, milanholemans approved these changes
Nice! 👏

2023-11-30 08:34 UTC, waldekmastykarz approved these changes

2023-11-30 08:34 UTC, merged