Cli for Microsoft 365 release blog post 7.6
pnp/blog pull request #1790
Opened 2024-03-28 02:25 UTC by Adam-it

## Category

- [X] New article

2024-03-29 09:41 UTC, milanholemans requested changes
Cool stuff @Adam-it! A few tiny comments from my side.

2024-03-29 09:41 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Microsoft has announced that SharePoint Add-Ins and Azure ACS will be retired and as a result will stop working for new tenants as of November 1st, 2024 and they will stop working for existing tenant
```suggestion
Microsoft has announced that SharePoint Add-Ins and Azure ACS will be retired and as a result will stop working for new tenants as of November 1st, 2024 and they will stop working for existing tenants as of April 2nd, 2026. It's important to remember those dates and migrate your existing Add-in projects to SharePoint Framework-based solutions. In a large tenant that has many customizations, it may be hard to find all the places that require your attention. Thankfully CLI for Microsoft 365 may be the answer to that problem.
```

2024-03-29 09:41 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Besides all these new commands, we've also made some changes to the existing commands. A lot of bugs have been fixed and the codebase has been polished. Some of our existing commands also got improve
Sounds a bit less dramatic 😄 

```suggestion
Besides all these new commands, we've also made some changes to the existing commands. A few bugs have been fixed and the codebase has been polished. Some of our existing commands also got improved like the `spo folder add/set` commands that now have the possibility to set the folder color. Another great example is the `spo site recyclebinitem restore` that now has two new options that allow you to restore all items from the first and/or second-stage recycle bin.
```

2024-03-29 09:41 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Besides all these new commands, we've also made some changes to the existing commands. A lot of bugs have been fixed and the codebase has been polished. Some of our existing commands also got improve
Could we also list these commands at the bottom of this section as we do with other sections? This will increase the click-through.

2024-03-29 13:27 UTC, Adam-it commented
> Cool stuff @Adam-it! A few tiny comments from my side.
done ✅

2024-03-29 13:44 UTC, Jwaegebaert approved these changes
Awesome work on this @Adam-it! Left a few pointers that could be interesting but nothing to big.

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To list all threatassessment simply run:
```suggestion
To list all threat assessments, simply run:
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +### New purview threatassessment commands
```suggestion
### New Purview threat assessment commands
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Or to Create a url threat assessment run:
```suggestion
Or to Create a URL threat assessment run:
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +### Generate Azure DevOps Pipeline for a SharePoint Framework project
Maybe an idea to shorten the heading?

```suggestion
### Generate Azure DevOps Pipeline for a SPFx project
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project with deployment to a site collection app catalog:
```suggestion
To add an Azure DevOps Pipeline for a SPFx project with deployment to a site collection app catalog:
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project with `user` login method triggered on push to `dev` branch:
```suggestion
To add an Azure DevOps Pipeline for a SPFx project with `user` login method triggered on push to `dev` branch:
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project triggered on push to `main`, simply run:
```suggestion
To add an Azure DevOps Pipeline for a SPFx project triggered on push to `main`, simply run: 
```

2024-03-29 13:44 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +One of our contributors added a new script that allows us to get information about retirement-related components from a selected tenant. It covers key elements such as event receivers, SharePoint Add
No comment, just a kudos on this section! 👏

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +The release includes additional management features for purview. We added two new commands that will allow you to list and remove threat assessments. Let's see it in action.
Let's write Purview with capital P as it's a product name

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +You may also filter them by type, for example, to list threat assessments of type mail you may run:
Simplify by removing "you may"

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Or to Create a url threat assessment run:
Also, a lowercase c in create

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +### Generate Azure DevOps Pipeline for a SharePoint Framework project
Then it should be "an SPFx"

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project triggered on push to `main`, simply run:
"an SPFx"

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project with `user` login method triggered on push to `dev` branch:
"an SPFx"

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project with deployment to a site collection app catalog:
"an SPFx"

2024-03-29 15:56 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Microsoft has announced that SharePoint Add-Ins and Azure ACS will be retired and as a result will stop working for new tenants as of November 1st, 2024 and they will stop working for existing tenant
Let's decide if we spell add-ins as Add-Ins or Add-ins and use it consistently throughout

2024-03-30 00:50 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +The release includes additional management features for purview. We added two new commands that will allow you to list and remove threat assessments. Let's see it in action.
```suggestion
The release includes additional management features for Purview. We added two new commands that will allow you to list and remove threat assessments. Let's see it in action. 
```

2024-03-30 00:51 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +You may also filter them by type, for example, to list threat assessments of type mail you may run:
```suggestion
You may also filter them by type, for example, to list threat assessments of type mail run:
```

2024-03-30 00:51 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Or to Create a url threat assessment run:
```suggestion
Or to create a url threat assessment run:
```

2024-03-30 00:52 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +### Generate Azure DevOps Pipeline for a SharePoint Framework project
```suggestion
### Generate Azure DevOps Pipeline for an SPFx project
```

2024-03-30 00:52 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project triggered on push to `main`, simply run:
```suggestion
To add an Azure DevOps Pipeline for an SPFx project triggered on push to `main`, simply run: 
```

2024-03-30 00:54 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project with `user` login method triggered on push to `dev` branch:
```suggestion
To add an Azure DevOps Pipeline for an SPFx project with `user` login method triggered on push to `dev` branch:
```

2024-03-30 00:55 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +To add an Azure DevOps Pipeline for a SharePoint Framework project with deployment to a site collection app catalog:
```suggestion
To add an Azure DevOps Pipeline for an SPFx project with deployment to a site collection app catalog:
```

2024-03-30 00:56 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +Microsoft has announced that SharePoint Add-Ins and Azure ACS will be retired and as a result will stop working for new tenants as of November 1st, 2024 and they will stop working for existing tenant
```suggestion
Microsoft has announced that SharePoint Add-ins and Azure ACS will be retired and as a result will stop working for new tenants as of November 1st, 2024 and they will stop working for existing tenants as of April 2nd, 2026. It's important to remember those dates and migrate your existing Add-in projects to SharePoint Framework-based solutions. In a large tenant that has many customizations, it may be hard to find all the places that require your attention. Thankfully CLI for Microsoft 365 may be the answer to that problem.
```

2024-03-30 00:56 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +One of our contributors added a new script that allows us to get information about retirement-related components from a selected tenant. It covers key elements such as event receivers, SharePoint Add
```suggestion
One of our contributors added a new script that allows us to get information about retirement-related components from a selected tenant. It covers key elements such as event receivers, SharePoint Add-ins, and Azure Access Control Service (ACS). If you are eager to find out more check out the [script in our docs](https://pnp.github.io/cli-microsoft365/sample-scripts/spo/sp-add-ins-and-azure-acs-retirement-report/).
```

2024-03-30 00:58 UTC, Adam-it commented
@waldekmastykarz done ✅
@Jwaegebaert done ✅

2024-03-31 11:18 UTC, martinlingstuyl requested changes
One tiny comment. Well done!

2024-03-31 11:18 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
> +The release includes additional management features for Purview. We added two new commands that will allow you to list and remove threat assessments. Let's see it in action.
```suggestion
The release includes additional management features for Purview. We added two new commands that will allow you to list and create threat assessments. Let's see it in action. 
```

2024-03-31 12:02 UTC, merged