New Blog | CLI for M365 - Release - v7.7
pnp/blog pull request #1817
Opened 2024-04-24 16:41 UTC by arjunumenon

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

This is a Pull Request which has the release announcement of new version of CLI for Microsoft 365 which is v7.7

2024-04-25 22:37 UTC, Adam-it approved these changes
@arjunumenon awesome work!
I added some small comments

2024-04-25 22:37 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have just published a new version of CLI for Microsoft 365. [CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsoft 365 tena
```suggestion
We have just published a new minor version of CLI for Microsoft 365. [CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsoft 365 tenant and SharePoint Framework projects. This minor release introduces several new commands that will enhance the quality of your Microsoft 365 experience.
```

2024-04-25 22:37 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +m365 spe containertype add
this actually will not work. Why do we give only the command and not the working example as we used to do. 
for example we could provide this line that will allow to create a new trial Container Type for an app 
```
m365 spe containertype add --name 'trial container' --applicationId '1b3b8660-9a44-4a7c-9c02-657f3ff5d5ac' --trial
```

2024-04-25 22:37 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have added new command called `m365 spo contenttype sync` which adds a published content type from the content type hub to a site or sync its latest changes. This command is going to be useful if
```suggestion
We have added a new command called `m365 spo contenttype sync` which adds a published content type from the content type hub to a site or syncs its latest changes. This command is going to be useful if you want to push the changes that you have done in the ContentType Hub to the sites where the content type is being used.
```

2024-04-25 22:37 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +Curious about what lies ahead? Were excited to share some of our ongoing projects and initiatives. We have some commands pertaining to the [Microsoft Entra Privileged Identity Management (PIM)](https
```suggestion
Curious about what lies ahead? We are excited to share some of our ongoing projects and initiatives. We have some commands pertaining to the [Microsoft Entra Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure) and [SharePoint Embedded (SPE)](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/overview) commands which are in the pipeline and will be released in the upcoming versions.
```

2024-04-26 21:32 UTC, milanholemans requested changes
Cool stuff @arjunumenon! Made a few comments while reading.

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +date: 2024-04-23T08:00:00.000Z
Usually we take as date, the date of the release (April 30)

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +m365 entra pim role assignment add
You should at least specify a roleDefinitionName or roleDefinitionId right?

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have added new command called `m365 spo contenttype sync` which adds a published content type from the content type hub to a site or sync its latest changes. This command is going to be useful if
```suggestion
We have added new command called `m365 spo contenttype sync` which adds a published content type from the content type hub to a site or sync its latest changes. This command will be useful if you want to push the changes you have done in the content type hub to the sites where the content type is being used.
```

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +m365 spo contenttype sync
This command cannot be invoked without options.

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +For more information, refer the documentation for [`m365 spo contenttype sync`](https://pnp.github.io/cli-microsoft365/cmd/spo/contenttype/contenttype-sync/)
```suggestion
For more information, refer the documentation for [m365 spo contenttype sync](https://pnp.github.io/cli-microsoft365/cmd/spo/contenttype/contenttype-sync/)
```

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have extended the SharePoint Framework commands so that it supports the latest version of the SharePoint Framework which is `v1.19.0-beta.0`. For more information on the commands, refer the docume
```suggestion
We have extended the SharePoint Framework commands so that it supports the latest beta version of the SharePoint Framework which is `v1.19.0-beta.0`. For more information on the commands, refer to the documentation,
```

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +- [spfx project doctor](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-doctor)
```suggestion
- [m365 spfx project doctor](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-doctor)
```

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have also fixed bugs for the SharePoint Online commands and added new features to the existing commands. Some of the commands which we have modified include `m365 spo page set`, `m365 spo site hub
```suggestion
We have also fixed a few bugs for the SharePoint Online commands and added new features to the existing commands. Some of the commands which we have modified include `m365 spo page set`, `m365 spo site hubsite connect`, `spo site hubsite disconnect`. For more information on the commands, refer to the documentation,
```

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +- [spo site hubsite disconnect](https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-hubsite-disconnect)
```suggestion
- [m36 spo site hubsite disconnect](https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-hubsite-disconnect)
```

2024-04-26 21:32 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We value your feedback and are eager to hear from you. If you have any suggestions for improvement or want to engage with our community, you can reach out to us on [GitHub](https://github.com/pnp/cli
Seems like a duplicate line from the one above.

2024-04-27 06:22 UTC, martinlingstuyl requested changes
Awesome @arjunumenon, 🤙 do checkout my comments.

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +### New SharePoint Embeded Container Commands
```suggestion
### New SharePoint Embedded Container Commands
```

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +This release of [CLI for Microsoft 365](https://aka.ms/cli-m365) includes introduction of SharePoint embedded (SPE) container commands which will have various commands which will help you to manage y
This sentence is a bit weird. Could you rephrase? We're only introducing some container commands now. The part about file (etc) commands is coming later, maybe add that as a separate sentence?

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have added new command called `m365 spo contenttype sync` which adds a published content type from the content type hub to a site or sync its latest changes. This command is going to be useful if
```suggestion
We have added a new command that adds a published content type from the content type hub to a site or syncs its latest changes. This command is going to be useful if you want to push the changes which you have done in the ContentType Hub to the sites where the content type is being used.
```

Slightly shorter...

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +Apart from the above changes, we have also optimized the command code bases and fixed some bugs. If you are eager to go over all of the details and improvements added in this release, do not hesitate
```suggestion
Apart from the above changes, we have also optimized the command code base and fixed some bugs. If you are eager to go over all of the details and improvements added in this release, do not hesitate to check out the [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v770) to find out more.
```

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +Curious about what lies ahead? Were excited to share some of our ongoing projects and initiatives. We have some commands pertaining to the [Microsoft Entra Privileged Identity Management (PIM)](https
```suggestion
Curious about what lies ahead? Were excited to share some of our ongoing projects and initiatives. We have some commands pertaining to [Microsoft Entra Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure) and [SharePoint Embedded (SPE)](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/overview) which are in the pipeline and will be released in the upcoming versions.
```

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +Right now, there are over 49 opened PRs with new awesome features that will be soon added to CLI for Microsoft 365, and [58 issues that are up for grabs](https://github.com/pnp/cli-microsoft365/issue
```suggestion
Right now, there are over 49 opened PRs with new awesome features that will soon be added to CLI for Microsoft 365, and [58 issues that are up for grabs](https://github.com/pnp/cli-microsoft365/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22). We're working hard to bring you even more exciting features and improvements in the next release. 
```

2024-04-27 06:22 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +Experience the power of CLI for Microsoft 365 by getting the latest release from npm:
```suggestion
Experience the power of the CLI for Microsoft 365 by getting the latest release from npm:
```

2024-04-27 19:51 UTC, Jwaegebaert requested changes
Hey @arjunumenon, great job! I dropped some extra tips. Personally, I'm not really into how the headers are used now. Repeating the command you'll discuss and then pulling explanations from MS Docs makes it a bit monotonous to read. Keep up the good work though, looking forward to seeing how it all turns out!

2024-04-27 19:51 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +This release of [CLI for Microsoft 365](https://aka.ms/cli-m365) includes introduction of SharePoint embedded (SPE) container commands which will have various commands which will help you to manage y
```suggestion
This release of [CLI for Microsoft 365](https://aka.ms/cli-m365) includes the introduction of SharePoint Embedded (SPE) container commands which will have various commands which will help you to manage your containers, files, permissions and many more.
```

2024-04-27 19:51 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +This release of [CLI for Microsoft 365](https://aka.ms/cli-m365) includes introduction of the Privileged Identity Management (PIM) commands that allow you to manage the PIM settings for users and gro
```suggestion
This release of [CLI for Microsoft 365](https://aka.ms/cli-m365) includes the introduction of the Privileged Identity Management (PIM) commands that allow you to manage the PIM settings for users and groups in your Microsoft Entra tenant.
```

2024-04-27 19:51 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +For creating a new Container Type for your app, run:
```suggestion
To create a new Container Type for your app, run:
```

2024-04-27 19:51 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +We have also fixed bugs for the SharePoint Online commands and added new features to the existing commands. Some of the commands which we have modified include `m365 spo page set`, `m365 spo site hub
```suggestion
We have also fixed bugs for the SharePoint Online commands and added new features to the existing commands. Some of the commands which we have modified include `m365 spo page set`, `m365 spo site hubsite connect`, and `spo site hubsite disconnect`. For more information on the commands, refer the documentation,
```

2024-04-27 19:51 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
> +- [spo site hubsite disconnect](https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-hubsite-disconnect)
I guess `m365` instead of `m36` 😄

2024-04-29 06:04 UTC, arjunumenon reviewed
Thanks Adam, Milan, Martin and Jasey for your review and comments. Changes have been made and has been pushed already.

2024-04-30 06:27 UTC, merged