Added new major version v8 for CLI for M365
pnp/blog pull request #1885
Opened 2024-07-27 13:16 UTC by arjunumenon

## Category

- [ ] Content fix
- [x] New article

## Related issues

N/A

## Contents of the Pull Request

This is a PR where we have created a PR for the new release of CLI for Microsoft 365 (v8). _This will be merged only once we have the release action is completed_

2024-07-27 23:27 UTC, milanholemans requested changes
Well done @arjunumenon! Made a few remarks while reading it.

One thing we should do: when showing command samples, we now use inline code (using single backtick). To improve the readability, I suggest we use a full line code block like we always do (using 3 backticks).

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +The endpoint that we are using in the command `spo group member add` is changed. With this change some of the output which the command outputs is also changed. The return values changed include prope
```suggestion
The endpoint that we are using in the command `spo group member add` is changed. With this change some of the output is also changed. The return values changed include properties like `DisplayName`, `User`, etc. You can get more details from [here](https://pnp.github.io/cli-microsoft365/v8-upgrade-guidance#updated-command-output-of-spo-group-member-add).
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +The endpoint that we are using in the command `spo group member add` is changed. With this change some of the output which the command outputs is also changed. The return values changed include prope
To improve clickthrough, I always recommend adding links on command names.

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +The API endpoint which is used for the command `flow list` is also changed due to the deprecation of the older endpoint. With this change, property outputs like `displayName` will be changed to `prop
To improve clickthrough, I always recommend adding links on command names.

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +The API endpoint which is used for the command `flow list` is also changed due to the deprecation of the older endpoint. With this change, property outputs like `displayName` will be changed to `prop
Most of the output changed only when running the command as admin.

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We had released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions got [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/projec
```suggestion
We released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions: [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-azuredevops-pipeline-add/) and [GitHub Workflow](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-github-workflow-add/). In this version, we also have added a readymade script in our docs so that the users can easily invoke the script which will generate the needed YAML file based on your parameter value, be it GitHub Workflows or Azure DevOps. This would help the users minimize their effort to create the YAML file from scratch if they want to have a CI/CD pipeline enabled for their SPFx projects.  You can get more details from [here](https://pnp.github.io/cli-microsoft365/sample-scripts/spo/add-ci-cd-pipeline/).
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +You can get more details about the command from [here](https://pnp.github.io/cli-microsoft365/cmd/spo/contenttype/contenttype-field-list/)
Usually, we list it now as:

For more information check the following resources:

- [m365 entra pim role request list](https://pnp.github.io/cli-microsoft365/cmd/entra/pim/pim-role-request-list)
- [m365 entra pim role assignment eligibility list](https://pnp.github.io/cli-microsoft365/cmd/entra/pim/pim-role-assignment-eligibility-list)

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +### Attendance report and message management in Microsoft Teams
```suggestion
### Microsoft Teams
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +You can get more details about the command from [here](https://pnp.github.io/cli-microsoft365/cmd/teams/meeting/meeting-attendancereport-get/).
Also here, let's list it as:

For more information check the following resources:

- [m365 entra pim role request list](https://pnp.github.io/cli-microsoft365/cmd/entra/pim/pim-role-request-list)
- [m365 entra pim role assignment eligibility list](https://pnp.github.io/cli-microsoft365/cmd/entra/pim/pim-role-assignment-eligibility-list)

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +For getting the specified attendance report made for another user and Microsoft Teams meeting with given id, run :
```suggestion
For getting the specified attendance report made for the currently signed-in user and Microsoft Teams meeting with the given id, run: 
`m365 teams meeting attendancereport get --meetingId MSo1N2Y5ZGFjYy03MWJmLTQ3NDMtYjQxMy01M2EdFGkdRWHJlQ --id a8634e64-3147-4a56-9b19-cc822e9c7972`
For getting the specified attendance report made for another user and Microsoft Teams meeting with given id, run: 
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +#### Removing a message from the Microsoft Teams team channel
```suggestion
#### Removing a message from a Microsoft Teams team channel
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +For removing a message using channel display names, run :
```suggestion
For removing a message by using channel ID, run: 
`m365 teams message remove --teamId 5f5d7b71-1161-44d8-bcc1-3da710eb4171 --channelId 19:4a95f7d8db4c4e7fae857bcebe0623e6@thread.tacv2 --id 1540747442203`

For removing a message using channel display names, run:
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +You can get more details about the command from [here](https://pnp.github.io/cli-microsoft365/cmd/teams/message/message-remove/).
Also here, let's list it as:

For more information check the following resources:

- [m365 entra pim role request list](https://pnp.github.io/cli-microsoft365/cmd/entra/pim/pim-role-request-list)
- [m365 entra pim role assignment eligibility list](https://pnp.github.io/cli-microsoft365/cmd/entra/pim/pim-role-assignment-eligibility-list)

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We all have been using CLI for Microsoft 365 from Azure Cloud Shell since we will have CLI for Microsoft 365 already baked into Azure Cloud Shell. For the past week, there was an issue when we tried
```suggestion
CLI for Microsoft 365 has been installed by default in Azure Cloud Shell for a couple of years. For the past weeks, there was an issue when we tried to run the CLI for Microsoft 365 from Azure Cloud shell. In this version, we have fixed the issue and now you can run the CLI for Microsoft 365 from Azure Cloud shell without any issues.
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +There was a bug when we tried to list the flows using the admin account. Now this issue is fixed and you can list the flows using the admin account without any issues. The issue was because the API t
Isn't this already covered above?

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +In this version, we have added the ability to set many more properties related to the notifications to the Entra group so that tenant admins can easily manage while using the scripts for provisioning
```suggestion
In this version, we have added the ability to set many more properties related to the notifications to the Microsoft Entra group so that owners can easily manage while using the scripts for provisioning or managing the Microsoft Entra Groups.
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We have added the ability to remove the app permission from your Entra app even if you mention it in the scope in an unqualified way (like `Sites.Read.All` instead of `https://graph.microsoft.com/Sit
```suggestion
We have added the ability to remove the app permission from your Microsoft Entra app even if you mention it in the scope in an unqualified way (like `Sites.Read.All` instead of `https://graph.microsoft.com/Sites.Read.All`). This will help users easily remove app permissions from the Entra app.
```

2024-07-27 23:27 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
```suggestion
- [Adam Wójcik](https://github.com/Adam-it)
- [János Dojcsák](https://github.com/dojcsakj)
- [Jasey Waegebaert](https://github.com/Jwaegebaert)
- [Martin Machacek](https://github.com/MartinM85)
- [Mathijs Verbeeck](https://github.com/MathijsVerbeeck)
- [Milan Holemans](https://github.com/milanholemans)
- [Nello D'Andrea](https://github.com/ferrarirosso)
- [Saurabh Tripathi](https://github.com/Saurabh7019)
- [Waldek Mastykarz](https://github.com/waldekmastykarz)
```

2024-07-28 06:10 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +date: 2024-08-01T06:00:00.000Z
I agree 👍. I remember solving the not published issue twice already 🙂

2024-07-28 07:14 UTC, arjunumenon commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +Once a year we take the opportunity to look at all of the functionality that we have in the CLI and see how we can make it more consistent and intuitive. Typically, this leads to breaking changes. We
Good point. Since we do have couple of  breaking changes, do you think we will give it as a section here?

2024-07-28 07:16 UTC, Adam-it approved these changes
@arjunumenon awesome work. Actually I don't have much to add as @milanholemans covered most of the things 👏.
I have only a single suggestion that in the 'Whats Next' we could also mention the upcoming v9 which we want to release in a few months with a lot of improvements which are connected to breaking changes.
Other than that awesome work 👏👏. You should write more blog posts 😍🤩

2024-07-28 07:16 UTC, Adam-it commented on .frontmatter/database/mediaDb.json
@arjunumenon what is this and why do we need to change this?
TBH I have never updated this one 😅

2024-07-28 07:30 UTC, arjunumenon commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +You can get more details about the command from [here](https://pnp.github.io/cli-microsoft365/cmd/spo/contenttype/contenttype-field-list/)
This is more neat 👍

2024-07-28 17:52 UTC, arjunumenon commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +There was a bug when we tried to list the flows using the admin account. Now this issue is fixed and you can list the flows using the admin account without any issues. The issue was because the API t
Not exactly. Before it was added along with the breaking change. Have not given details on the changes per say.

2024-07-28 18:13 UTC, arjunumenon commented on .frontmatter/database/mediaDb.json
I think that has something to do with FrontMatter extension which is being used. I had updated an image for the new release post. So with that, I guess the frontmatter updates the json file with the image information. 
Timeline suggests that updation of the image updates this file as well.

2024-07-28 18:33 UTC, arjunumenon commented
Thanks @Adam-it @milanholemans for the review. I have done the modification and have given comments. Let me know if you feel any more modification on that

2024-07-30 07:59 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +Once a year we take the opportunity to look at all of the functionality that we have in the CLI and see how we can make it more consistent and intuitive. Typically, this leads to breaking changes. We
Isn't there already a heading talking about the breaking changes below?

2024-07-30 08:16 UTC, Jwaegebaert requested changes
Hey @arjunumenon, pardon for the late review. I've left a few comments you can take a look at. Shouldn't be anything too major.

2024-07-30 08:16 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions for [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-az
```suggestion
We released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions for [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-azuredevops-pipeline-add/) and [GitHub Workflow](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-github-workflow-add/). In this version, we also have added a readymade script in our docs so that the users can easily invoke the script which will generate the needed YAML file based on your parameter value, be it GitHub Workflows or Azure DevOps. This would help the users minimize their effort to create the YAML file from scratch if they want to have a CI/CD pipeline enabled for their SPFx projects.  You can get more details from [here](https://pnp.github.io/cli-microsoft365/sample-scripts/spo/add-ci-cd-pipeline/).
```

2024-07-30 08:16 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +For retrieving the fields associated with a site content type, run :
```suggestion
For retrieving the fields associated with a site content type, run: 
```

2024-07-30 08:16 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +For retrieving the fields associated with a list content type in the Documents library, run :
```suggestion
For retrieving the fields associated with a list content type in the Documents library, run:
```

2024-07-30 08:16 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +For getting the specified attendance report made for another user and Microsoft Teams meeting with given id, run :
```suggestion
For getting the specified attendance report made for another user and Microsoft Teams meeting with the given ID, run: 
```

2024-07-30 09:49 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +Once a year we take the opportunity to look at all of the functionality that we have in the CLI and see how we can make it more consistent and intuitive. Typically, this leads to breaking changes. We
In this release we only have 2 breaking changes:
- flow list
- spot group member add

2024-07-30 12:39 UTC, arjunumenon commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions for [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-az
I am sorry I did not quite understand the change. Is the _**suggested change**_ same as what it is there already? Am I missing something 🤔

2024-07-30 12:45 UTC, arjunumenon commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +If you need more help getting started or want more details about the commands, architecture, or project, go to [aka.ms/cli-m365](https://aka.ms/cli-m365). If you see any room for improvement, please,
oops

2024-07-30 14:57 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions for [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-az
In the sentence `This would help the users minimize  their effort to create the YAML file from scratch if they want to have a CI/CD pipeline enabled for their SPFx projects` there are two spaces between `minimize` and `their`

2024-07-30 16:25 UTC, arjunumenon commented on .frontmatter/database/mediaDb.json
> +{"users":{"luise":{"onedrive":{"dev":{"pnpblog":{"content":{"weekly-agenda":{"23-09-11":{"images":{"weeklyagenda37.png":{}}},"23-09-18":{"images":{"weeklyagenda38.png":{}}},"23-10-16":{"images":{}},"
That is a Frontmatter file which keeps the metadata associated when you add an image to the project. In this case, I had added a new image and that is why this file has got changed. You can see [this issue](https://github.com/estruyf/vscode-front-matter/issues/606) which is there in FrontMatter issue list where folks explain about that

2024-07-30 22:51 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/images/banner-cli-m365.png
You can easily fix this issue by clicking on a link to another page and clicking "home" again.

2024-07-31 08:59 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/index.md
> +We released a new command for adding CI/CD configurations to your existing SPFx projects in our previous versions for [Azure DevOps](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-az
there is also double space in `....SPFx projects.  You can get more details from ....`. just Before you we should have single space

2024-07-31 08:59 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/images/banner-cli-m365.png
do we want to fixup this screenshot before merge?

2024-07-31 11:44 UTC, merged

2024-07-31 15:53 UTC, arjunumenon commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-0/images/banner-cli-m365.png
Somehow I am still facing an issue. Now instead of a no image, I am getting a black block. Let us troubleshoot in the issue which we have opened and see that. 

![image](https://github.com/user-attachments/assets/597ebf63-0632-428a-8ca7-90082f2ced0b)