Update April/May/June/July Office add-in community call
pnp/blog pull request #1887
Opened 2024-07-30 10:00 UTC by MingjiaLiu1995

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request
Update April/May/June/July Office add-in community call blog

2024-07-30 10:04 UTC, MingjiaLiu1995 commented
@lindalu-MSFT @davidchesnut Hi Linda and David, would you please help me review the blogs of recent community calls? For some reasons I can not add you as reviewers in this pr. Please let me know if there is anything. Thanks!

2024-07-30 19:27 UTC, lindalu-MSFT requested changes
Need to fix some of these things:

- Remove /en-us/ in links
- Clean up link text (extra unnecessary text makes is annoying to screen reader users)
- a few voice and style gotchas
- other minor edits

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +Obfuscation and putting code on the server side (like Azure functions) are pretty much the fundamental ways to keep your code private. Since Office Add-ins are basically web applications, they are su
```suggestion
Obfuscation and putting code on the server side (like Azure functions) are the fundamental ways to keep your code private. Since Office Add-ins are basically web applications; they are subject to the same code protection strategies as any web application.
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +**I missed my question regarding source code protection in the call March 13th. I have submitted the question for two meetings now without any answer. I would love to hear your views on how to best p
```suggestion
**I missed my question regarding source code protection in the call March 13th. I have submitted the question for two meetings now without any answer. I would love to hear your views on how to best protect the source code for an Office Add-in (keeping it safe from someone copying it and selling it for their own). I know about code obfuscation, and I know some code can be put on the server side, but I would love to hear some best practice on this topic from the experts.**
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +You can use one of several methods to deploy your Office Add-in for distribution to users. [Deploy and publish Office Add-ins - Office Add-ins | Microsoft Learn​](https://learn.microsoft.com/en-us/of
```suggestion
To learn about the several methods used to deploy your Office Add-in for distribution to users, see [Deploy and publish Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/publish/publish).
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +Thank you very much for your request here. We currently don't have such event for Word document save operations. We will keep you informed when we have updates on this. Please also submit a request a
```suggestion
Thank you very much for your request here. We currently don't have such event for Word document save operations. We'll keep you informed when we have updates on this. Please also submit a request and describe your use case on the [Microsoft 365 Developer Platform Ideas Forum]( https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +Currently, within Office.js, there isn’t a direct method to determine whether event-based activation is supported or if the add-in was installed directly via AppSource by an end user. Additionally, o
```suggestion
Currently, within Office.js, there isn’t a direct method to determine whether event-based activation is supported or if the add-in was installed directly via AppSource by an end user. Additionally, our messaging to users on Office clients does not reflect/call out the installation source of the add-in. Our team is exploring potential workarounds for this situation. We'll keep you informed with updates once we have thoroughly tested any proposed solutions. 
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +Thank you for your request here. Currently we don't have such support for Outlook Mobile. We will keep you informed when we have updates on this.​
```suggestion
Thank you for your request here. Currently we don't have such support for Outlook Mobile. We'll keep you informed when we have an update.​
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +* [Office Add-ins platform overview - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
```suggestion
* [Office Add-ins platform overview](https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +* [Create custom functions in Excel - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
```suggestion
* [Create custom functions in Excel](https://learn.microsoft.com/office/dev/add-ins/excel/custom-functions-overview)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +* [Tutorial: Share data and events between Excel custom functions and the task pane - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-e
```suggestion
* [Tutorial: Share data and events between Excel custom functions and the task pane](https://learn.microsoft.com/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +**Hi Team, We are trying to review and compile the list of Office addins from Office 365 Admin center. The goal is to review the addins that are being reported and then have those packaged up in Intu
```suggestion
**Hi Team, We are trying to review and compile the list of Office Add-ins from Office 365 Admin center. The goal is to review the add-ins that are being reported and then have those packaged up in Intune for better management (from an Enterprise POV). We have combo of 64 and 86 Office architecture. Any inputs on best practice methods available out there to Manage Office addins will be greatly appreciated. Thank you.**
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +Thanks for your question. To better help, our team would like to understand more details of your scenario. Would you please go  [Issues · OfficeDev/office-js (github.com)](https://github.com/officede
```suggestion
Thanks for your question. To better help, our team would like to understand more details of your scenario. Please go to the [OfficeDev/office-js issues repo on GitHub](https://github.com/officedev/office-js/issues) to submit your question so that the team can engage with you.
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +Thanks for your question. To better help, our team would like to understand more details of your scenario. Would you please go  [Issues · OfficeDev/office-js (github.com)](https://github.com/officede
```suggestion
Thanks for your question. To better help, our team would like to understand more details of your scenario. Please go to the [OfficeDev/office-js issues repo on GitHub](https://github.com/officedev/office-js/issues) to submit your question so that the team can engage with you.
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-05-08/index.md
> +* [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/unified-manifest-overview)
```suggestion
* [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/office/dev/add-ins/develop/unified-manifest-overview)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-05-08/index.md
> +* [Build an Outlook add-in with the unified manifest](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-json-manifest)
```suggestion
* [Build an Outlook add-in with the unified manifest](https://learn.microsoft.com/office/dev/add-ins/quickstarts/outlook-quickstart-json-manifest)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-05-08/index.md
> +* [Create Office Add-in projects using Teams Toolkit](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/teams-toolkit-overview)
```suggestion
* [Create Office Add-in projects using Teams Toolkit](https://learn.microsoft.com/office/dev/add-ins/develop/teams-toolkit-overview)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-05-08/index.md
> +* [Convert xml to json manifest](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/convert-xml-to-json-manifest)
```suggestion
* [Convert xml to json manifest](https://learn.microsoft.com/office/dev/add-ins/develop/convert-xml-to-json-manifest)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-05-08/index.md
> +We do not have any dashboards to track which users are acquiring the apps for themselves. However, admin can run following cmdlet on all user mailbox to get list of add-in deployed for the user. This
```suggestion
We don't have any dashboards to track which users are acquiring the apps for themselves. However, admins can run the following cmdlet on all user mailbox to get list of add-ins deployed for the user. This will help admins get list of which apps are deployed and to which users. For more info, see [Get-App (ExchangePowerShell)](https://learn.microsoft.com/powershell/module/exchange/get-app?view=exchange-ps) 
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-07-10/index.md
> +* [Learn more at the M365 App Compliance docs pages](https://learn.microsoft.com/en-us/microsoft-365-app-certification)
```suggestion
* [Learn more at the M365 App Compliance docs pages](https://learn.microsoft.com/microsoft-365-app-certification)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-07-10/index.md
> +* [View the getting started guide for Office, Teams, and SharePoint apps](https://docs.microsoft.com/en-us/microsoft-365-app-certification/docs/userguide)
```suggestion
* [View the getting started guide for Office, Teams, and SharePoint apps](https://docs.microsoft.com/microsoft-365-app-certification/docs/userguide)
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-07-10/index.md
> +You can use Graph api to get access to Excel application data in your Word add-in: [Excel workbooks and charts API overview - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/grap
```suggestion
To learn how to use Graph API to get access to Excel application data in your Word add-in, see [Excel workbooks and charts API overview](https://learn.microsoft.com/graph/excel-concept-overview). However, this doesn’t work if you want to get access to Word data from Excel, so you may consider using a server to communicate between. 
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-07-10/index.md
> +For Office add-in testing, we recommend you use the [Office-Addin-Mock](https://www.npmjs.com/package/office-addin-mock) library with JavaScript unit testing framework. You can find more examples her
```suggestion
For Office add-in testing, we recommend you use the [Office-Addin-Mock](https://www.npmjs.com/package/office-addin-mock) library with JavaScript unit testing framework. For more examples, see [Unit testing in Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/testing/unit-testing).
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-07-10/index.md
> +**Not related to compliance or certification but my question relates to Copilot for M365 and the new Add in platform: Will the new Add in platform allow customisations to Copilot or are the two compl
```suggestion
**Not related to compliance or certification but my question relates to Copilot for M365 and the new add-in platform: Will the new add-in platform allow customizations to Copilot or are the two completely different things. If so, how can we work with Copilot in our add-ins?**
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-07-10/index.md
> +We are investigating scenarios for how Copilot and Office Add-ins could work together, but have no public plans to share at this time.  If there are scenarios or functionality you'd like to suggest,
```suggestion
We are investigating scenarios for how Copilot and Office Add-ins could work together but have no public plans to share at this time.  If there are scenarios or functionality you'd like to suggest, please let us know through the [Microsoft 365 Developer Platform Ideas forum](https://aka.ms/m365dev-suggestions).
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +**Is it a good, relevant, smart idea to deploy an Office Add-in as an Aspire application using Blazor? (https://learn.microsoft.com/en-us/dotnet/aspire/)**
```suggestion
**Is it a good, relevant, smart idea to deploy an Office Add-in as an Aspire application using Blazor? (https://learn.microsoft.com/dotnet/aspire/)**
```

2024-07-30 19:27 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-04-10/index.md
> +**I would like to ask questions about word addin, we are developing an addin for word, excel and powerpoint online and desktop versions, we have taskpan addin working fine but we wanted to activate o
```suggestion
**I would like to ask questions about Word add-ins, we are developing an add-in for word, excel and PowerPoint online and desktop versions, we have taskpane add-in working fine but we wanted to activate our add-in on events such as save if it is on new Outlook desktop version.**
```

2024-08-01 09:32 UTC, MingjiaLiu1995 commented
@lindalu-MSFT Thanks Linda! Have committed all the suggestions.

2024-08-06 14:39 UTC, MingjiaLiu1995 commented
@lindalu-MSFT Hi Linda, do you know who is the maintainer of this repo? The pr is blocked because the link checker fails. I checked the errors and it seems that they all come from the whole branch but not this pr. Any suggestions on who I should talk with to get this approved? Thanks!

2024-08-06 16:38 UTC, lindalu-MSFT commented
> @lindalu-MSFT Hi Linda, do you know who is the maintainer of this repo? The pr is blocked because the link checker fails. I checked the errors and it seems that they all come from the whole branch but not this pr. Any suggestions on who I should talk with to get this approved? Thanks!

You can check with @davidchesnut who can likely help.

2024-08-06 21:02 UTC, merged

2024-08-06 21:03 UTC, LuiseFreese commented
I merged this, let's see if the site builds currently. If not, I will need to ask you to fix the files as they might contain invalid markdown. Example: don't provide a heading 1 with 1 # as that's already the title which is defined in the front matter.

2024-08-06 21:17 UTC, LuiseFreese commented
@MingjiaLiu1995 did you mean to submit all posts with draft true? This means they won't appear on the site.