August Office Add-ins community call
pnp/blog pull request #1908
Opened 2024-08-22 09:31 UTC by MingjiaLiu1995

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

> New article: Office Add-ins developer platform community call – August 14, 2024

2024-08-22 09:32 UTC, MingjiaLiu1995 commented
Hi @lindalu-MSFT , could you help me review this blog for August community call? Thanks!

2024-11-26 03:33 UTC, MingjiaLiu1995 commented
@lindalu-MSFT Hi Linda! Could you help with reviewing this pr for office add-in community call Aug/Sep/Oct/Nov blogs? Thanks!

2024-11-26 17:42 UTC, lindalu-MSFT requested changes

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-08-14/index.md
> +* **Install add-ins with Deeplink.** [Skylar Pan](https://www.linkedin.com/in/skylar-pan-4566617b/), Product Manager2, Microsoft.
```suggestion
* **Install add-ins with Deeplink.** [Skylar Pan](https://www.linkedin.com/in/skylar-pan-4566617b/), Senior Program Manager at Microsoft.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-08-14/index.md
> +The call was hosted by [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager, Microsoft.
```suggestion
The call was hosted by [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager at Microsoft.
```
For consistency, let's do this one way or the other!

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-08-14/index.md
> +* **Visual Studio Code extension for Office add-in update.** [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager at Microsoft.
```suggestion
* **Visual Studio Code extension for Office Add-in update.** [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager at Microsoft.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-08-14/index.md
> +**We are implementing NAA into our add-in that is reliant on graph calls, with NAA allowing for client-side graph calls what is the best way for fallback auth? Will we still have to have middle-tier
```suggestion
**We are implementing NAA into our add-in that is reliant on Microsoft Graph calls, with NAA allowing for client-side Graph calls what is the best way for fallback auth? Will we still have to have middle-tier server Graph calls to work with a fallback? We‘re hoping this isn’t the case.**
```
Let's be sure our branding is correct on customer submitted questions.

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-08-14/index.md
> +**If you send too many graph requests, you get sent a 429 response and a header that contains the time you should retry sending the request. If you attempt to make a request during this period, the c
```suggestion
**If you send too many Graph requests, you get sent a 429 response and a header that contains the time you should retry sending the request. If you attempt to make a request during this period, the call is still counted against throttling limits and the retry after gets extended. Though only used in rare situations, consistent calls while throttled will cause the app to get banned from accessing the tenant. However, for SharePoint, all the SharePoint driveItem throttling limits are defined per app per tenant, meaning if calls get throttled they are throttled for all users in a given tenant. The old suggested approach is to use a back off method, where the app sends no requests, until the header retry time, for all users. This was a lot easier when graph requests were made from a server and all graph request traffic was centralized. But having NAA, all the Graph calls are now in separate instances of the app, there is no way to coordinate a back-off method? Just wondering if the new NAA flow can account for this? Or if this is even a problem at all?**
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +AFor submission process, please check the related document [here](https://learn.microsoft.com/partner-center/marketplace-offers/plan-saas-offer), where it shows you how to plan a SaaS offer for the M
```suggestion
For submission process, see [Plan a SaaS offer for the commercial marketplace](https://learn.microsoft.com/partner-center/marketplace-offers/plan-saas-offer). If you have additional questions about Publish Center, you can post them in our [Microsoft Partner Community​](https://techcommunity.microsoft.com/category/PartnerCommunity).
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* Word API Update [04:56](https://youtu.be/cJK9rvCTeAY?t=296)
```suggestion
* Word API update [04:56](https://youtu.be/cJK9rvCTeAY?t=296)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* PowerPoint Preview APIs and Ribbon 1.1 API Updates [01:27](https://youtu.be/cJK9rvCTeAY?t=87)
```suggestion
* PowerPoint preview APIs and Ribbon 1.1 API updates [01:27](https://youtu.be/cJK9rvCTeAY?t=87)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* Visual Studio Code extension for Office Add-ins Public Preview [25:05](https://youtu.be/cJK9rvCTeAY?t=1505)
```suggestion
* Visual Studio Code extension for Office Add-ins public preview [25:05](https://youtu.be/cJK9rvCTeAY?t=1505)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* WXP Add-ins with the Unified manifest for Microsoft 365 Public Preview [27:02](https://youtu.be/cJK9rvCTeAY?t=1622)
```suggestion
* WXP Add-ins with the Unified manifest for Microsoft 365 public preview [27:02](https://youtu.be/cJK9rvCTeAY?t=1622)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +PowerPoint Preview APIs and Ribbon 1.1 API Updates
```suggestion

PowerPoint preview APIs and Ribbon 1.1 API updates
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* [M365 blog annoucement](https://devblogs.microsoft.com/microsoft365dev/announcing-the-office-add-ins-development-kit-for-visual-studio-code-public-preview/)
```suggestion
* [M365 blog announcement](https://devblogs.microsoft.com/microsoft365dev/announcing-the-office-add-ins-development-kit-for-visual-studio-code-public-preview/)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +AFor submission process, please check the related document [here](https://learn.microsoft.com/partner-center/marketplace-offers/plan-saas-offer), where it shows you how to plan a SaaS offer for the M
```suggestion
For the submission process, see [Plan a SaaS offer for the commercial marketplace](https://learn.microsoft.com/partner-center/marketplace-offers/plan-saas-offer). If you have additional questions about the Publish Center, you can post them in our [Microsoft Partner Community​](https://techcommunity.microsoft.com/category/PartnerCommunity).
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +Single Sign-On (SSO) Authentication: Since you're already working on SSO, you're setting up a way to authenticate users based on their existing Microsoft identity. This part of the setup confirms the
```suggestion
Single Sign-On (SSO) Authentication: Since you're already working on SSO, you're setting up a way to authenticate users based on their existing Microsoft identity. This part of the setup confirms the identity of the users. For the official documentation, see [Enable single sign-on (SSO) in an Office Add-in](https://learn.microsoft.com/office/dev/add-ins/develop/sso-in-office-add-ins?tabs=jsonmanifest).​
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +Yes, uploading your Excel Add-in distribution files to your Azure subscription's Storage account Blob Container in the $web folder is an appropriate and common practice. However, there's no way to pr
```suggestion
Yes, uploading your Excel Add-in distribution files to your Azure subscription's Storage account Blob Container in the $web folder is an appropriate and common practice. However, there's no way to prevent from other people getting access as the locations of these manifests are public.
```
Getting what? I assume "access?" Please clarify, this sentence seems to be missing a word.

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-10-09/index.md
> +The call was hosted by [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager2, Microsoft.
```suggestion
The call was hosted by [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager 2 at Microsoft.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-10-09/index.md
> +* **Install JS add-ins together with main app/COM add-ins on Win32** [Skylar Pan](https://www.linkedin.com/in/skylar-pan/), Senior Product Manager at Microsoft.
```suggestion
* **Install JS add-ins together with main app/COM add-ins on Win32** [Skylar Pan](https://www.linkedin.com/in/skylar-pan/), Senior Program Manager at Microsoft.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +The call was hosted by [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager2, Microsoft.
```suggestion
The call was hosted by [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager 2 at Microsoft.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +* **Q&A.** [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager2, Microsoft.
```suggestion
* **Q&A.** [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager 2 at Microsoft.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +* Word API Update [00:50]( https://youtu.be/hJ8fY2IxJKU?t=50)
```suggestion
* Word API update [00:50]( https://youtu.be/hJ8fY2IxJKU?t=50)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +* Excel API and Capability Update [13:39]( https://youtu.be/hJ8fY2IxJKU?t=819)
```suggestion
* Excel API and capability update [13:39]( https://youtu.be/hJ8fY2IxJKU?t=819)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +Word API Update
```suggestion

Word API update
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +Excel API and Capability Update
```suggestion
Excel API and capability update
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +Currently, in our mechanism, all add-ins are loaded when the application starts, and due to resource management, the app would not continuously check for new add-ins, and it would also need careful c
```suggestion
Currently, all add-ins are loaded when the application starts. Due to resource management, the app does not continuously check for new add-ins. If we were to provide such an API capability for add-ins to update the add-in registry, this would terminate the current add-in session. Please help us raise a new feature request in [our tech community](https://techcommunity.microsoft.com/category/microsoft365/ideas/microsoft365developerplatform) so that we can put it in our backlog and prioritize it properly based on the vote numbers.​
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +Graph API related information can be found [here](https://learn.microsoft.com/graph/api/resources/sharepoint?view=graph-rest-1.0​), where there are examples of how to get specific IDs related to shar
```suggestion
For more information about Graph APIs, see [Working with SharePoint sites in Microsoft Graph](https://learn.microsoft.com/graph/api/resources/sharepoint?view=graph-rest-1.0​). There are examples of how to get specific IDs related to SharePoint, and also how to further use these IDs to get the data you need. ​
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +We have launched events on Mobile which run in [compose mode](https://learn.microsoft.com/office/dev/add-ins/outlook/mobile-event-based?tabs=jsonmanifest). You can check and see if it's related to yo
```suggestion
We've launched events on Outlook mobile which run in [compose mode](https://learn.microsoft.com/office/dev/add-ins/outlook/mobile-event-based?tabs=jsonmanifest). You can check and see if it's related to your question. If not, please submit your question to GitHub so that we can understand more about your use case.
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +Is it possible to get a list of the open bugs/issues you are referring to? Our team frequently monitors GitHub for issues and triage bugs. In the meantime, here are some information you can stay curr
```suggestion
Is it possible to get a list of the open bugs/issues you are referring to? Our team frequently monitors GitHub for issues and triage bugs. In the meantime, for information on what's coming in New Outlook, see [Add-ins in the new Outlook for Windows](https://techcommunity.microsoft.com/blog/outlook/add-ins-in-the-new-outlook-for-windows/3954388) and [What's new in new Outlook for Windows](https://support.microsoft.com/office/what-s-new-in-new-outlook-for-windows-c4c33813-1e9a-4304-8499-90fe7f164bd1)
```

2024-11-26 17:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +We haven't got an answer from the owner team till now. Please stay tuned for the update.
```suggestion
We don't have an answer from the owner team yet but please stay tuned for the update.
```

2024-11-26 18:00 UTC, lindalu-MSFT requested changes

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-08-14/index.md
> +Authentication and authorization goes to eSTS service with login.microsoftonline.com  URL. This isn't a Graph API so it won't count towards Graph throttling limits which are different for different A
```suggestion
Authentication and authorization goes to eSTS service with a login.microsoftonline.com URL. This isn't a Graph API, so it won't count towards Graph throttling limits which are different for different APIs see [Microsoft Graph service-specific throttling limits](https://learn.microsoft.com/graph/throttling-limits).
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* **PowerPoint Preview APIs and Ribbon 1.1 API Updates** [Ester Bergen](https://www.linkedin.com/in/esterbergen/), Senior Product Manager at Microsoft.
```suggestion
* **PowerPoint Preview APIs and Ribbon 1.1 API updates** [Ester Bergen](https://www.linkedin.com/in/esterbergen/), Senior Product Manager at Microsoft.
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* **Word API Update** [Yun Wang](https://www.linkedin.com/in/airwangyun/), Principal Product Manager at Microsoft and [Steve Jin](https://www.linkedin.com/in/steve-jin-61b08011), Senior Product Manag
```suggestion
* **Word API updates** [Yun Wang](https://www.linkedin.com/in/airwangyun/), Principal Product Manager at Microsoft and [Steve Jin](https://www.linkedin.com/in/steve-jin-61b08011), Senior Product Manager at Microsoft.
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* **Visual Studio Code extension for Office Add-ins Public Preview** [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager2 at Microsoft.
```suggestion
* **Visual Studio Code extension for Office Add-ins public preview** [Mingjia Liu](https://www.linkedin.com/in/mingjia-liu-90a69a24a/), Product Manager2 at Microsoft.
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +* **WXP Add-ins with the Unified manifest for Microsoft 365 Public Preview** [Luyi Han](https://www.linkedin.com/in/luyihan/), Senior Product Manager at Microsoft.
```suggestion
* **WXP Add-ins with the Unified manifest for Microsoft 365 public preview** [Luyi Han](https://www.linkedin.com/in/luyihan/), Senior Product Manager at Microsoft.
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +AFor submission process, please check the related document [here](https://learn.microsoft.com/partner-center/marketplace-offers/plan-saas-offer), where it shows you how to plan a SaaS offer for the M
Note that for accessibility, link text can never be "here." You must spell out the target link. The standard format is "For information about blah, see [full title of article]{URL}.

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +Authorization via SaaS Fulfillment APIs: For authorization, you'll need to check if the user has an active subscription for your SaaS offer after they are authenticated. This involves using the Micro
```suggestion
Authorization via SaaS Fulfillment APIs: For authorization, you'll need to check if the user has an active subscription for your SaaS offer after they are authenticated. This involves using the Microsoft SaaS Fulfillment APIs, which allow you to verify subscription status. For more information, see [SaaS Fulfillment API](https://learn.microsoft.com/partner-center/marketplace-offers/partner-center-portal/pc-saas-fulfillment-life-cycle).​
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-09-11/index.md
> +You can set up a test account and add the necessary information to your critical test instructions. Please check [here](https://learn.microsoft.com/partner-center/marketplace-offers/add-in-submission
```suggestion
You can set up a test account and add the necessary information to your critical test instructions. For more information, see the [Store step-by-step submission guide](https://learn.microsoft.com/partner-center/marketplace-offers/add-in-submission-guide). 
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-10-09/index.md
> +* [Microsoft 365 Platform Community in YouTube](https://aka.ms/community/videos)
```suggestion
* [Microsoft 365 Platform Community on YouTube](https://aka.ms/community/videos)
```

2024-11-26 18:00 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2024-11-13/index.md
> +* [Microsoft 365 Platform Community in YouTube](https://aka.ms/community/videos)
```suggestion
* [Microsoft 365 Platform Community on YouTube](https://aka.ms/community/videos)
```

2024-11-26 18:02 UTC, lindalu-MSFT commented
So lots of little niggly things that I'm sure you'll pick up on and avoid in the future! Once you accept these edits, please assign to me again so I can do another edit pass to ensure we caught everything. 

https://learn.microsoft.com/style-guide/top-10-tips-style-voice

2024-11-27 03:34 UTC, MingjiaLiu1995 commented on content/office-add-ins-community-call/2024-09-11/index.md
> +Yes, uploading your Excel Add-in distribution files to your Azure subscription's Storage account Blob Container in the $web folder is an appropriate and common practice. However, there's no way to pr
Yes, getting access to the manifests

2024-11-27 05:58 UTC, MingjiaLiu1995 commented
> @MingjiaLiu1995 So lots of little niggly things that I'm sure you'll pick up on and avoid in the future! Once you accept these edits, please assign to me again so I can do another edit pass to ensure we caught everything.
> 
> https://learn.microsoft.com/style-guide/top-10-tips-style-voice

Thanks @lindalu-MSFT ! I have accepted all the edits.

And thanks for the guidance! Maybe I should try to get some suggestions from Copilot first with the guidance next time ;)

2024-11-27 18:23 UTC, lindalu-MSFT approved these changes

2024-12-09 08:47 UTC, MingjiaLiu1995 commented
Hi @LuiseFreese @VesaJuvonen, could you help merge this pr? For some reason the markdown check fails, but the errors are not from my edited part. But let me know if I miss something! Thanks

2024-12-11 11:07 UTC, merged