Cli for microsoft 365 release blog post v9
pnp/blog pull request #1916
Opened 2024-08-29 01:13 UTC by Adam-it

## Category

- [X] New article

2024-08-29 05:25 UTC, martinlingstuyl approved these changes
Looks great @Adam-it! No (serious) comments...can you believe it? 😀

2024-08-29 05:25 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-1/index.md
> +// TODO: add image
Dont forget the image 😀

2024-08-29 11:44 UTC, LuiseFreese commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-1/index.md
> +// TODO: add image
just a little sign of appreciation: You CLI people all totally rock and I love the consistency in which you keep shipping.

2024-08-29 11:59 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-1/index.md
> +// TODO: add image
Thanks @LuiseFreese, great to hear. Same with you by the way in all the things you do. Keep on rocking!

2024-08-29 20:09 UTC, milanholemans requested changes
Nice blog @Adam-it! I don't have much to add. Something we should probably recheck is if this is `v8.1` or `v9`. (probably the latter).

2024-08-29 20:09 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-1/index.md
> +And to update the multitenant organization display name and description, simply run:
```suggestion
To update the multitenant organization display name and description, simply run:
```

2024-08-29 20:09 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v8-1/index.md
> +One of the CLI for Microsoft 365 biggest advantages is to be able to connect to multiple accounts (tenants) and just switch connections when needed instead of having to log in and out every time. In
```suggestion
One of the biggest advantages of the CLI for Microsoft 365 is that it is able to connect to multiple accounts (tenants) and switch connections when needed instead of having to log in and out every time. In this release, we enhanced the `connection use` command in a way that it will present you a prompt with a list of all your connections so it is super easy to just pick the correct one and perform the switch. 
```

2024-08-29 20:12 UTC, Adam-it commented
> Nice blog @Adam-it! I don't have much to add. Something we should probably recheck is if this is `v8.1` or `v9`. (probably the latter).

Why should this be v9? I thought that we release v8,.1 and v9 shortly after

2024-08-29 20:14 UTC, milanholemans commented
I thought the plan was to merge the new login command in this release as well, no?

2024-08-31 19:14 UTC, milanholemans requested changes
I did another review and found a few spelling mistakes. Let's fix them before we publish this blog. Apart from that, it looks really good!

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +This major release is a reaction to an annoucement that the PnP Management Shell multi-tenant app will get removed on September 9. Previously you were able to use a this app to grant the needed permi
```suggestion
This major release is a reaction to an announcement that the PnP Management Shell multi-tenant app will be removed on September 9. Previously you were able to use this app to grant the needed permissions for your scripts or standard usage of CLI for Microsoft 365. Till now it was even used as the default login method. As mentioned at the beginning this multi-tenant app registration will be however deleted on September 9, 2024 which might have an impact on your existing scripts. Check the following [recording for more details](https://www.youtube.com/watch?v=VNgc4k_gCT0) on this announcement. Although using the PnP Management Shell was very convenient it wasn't the best approach that should be picked especially when running automated scripts on your tenant. This option will now go away to help customers improve their security posture by encouraging the use of single-tenant apps and just the needed scopes and permissions. CLI for Microsoft 365 already supports login over your own Entra app registration and we already have [guidance that will guide you through the process](https://pnp.github.io/cli-microsoft365/user-guide/using-own-identity). In this release, we introduced some features that might prove very helpful in adapting to this change.
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +This means that you will now need to set up your own Entra app registration before performing the initial login. You may do that in several ways. Either by doing it manually and we also included deta
```suggestion
This means that you will now need to set up your own Microsoft Entra app registration before performing the initial login. You may do that in several ways. Either by doing it manually, and we also included detailed [step-by-step documentation](https://pnp.github.io/cli-microsoft365/user-guide/using-own-identity#register-microsoft-entra-application-in-your-tenant) for that or you may use our new `setup` experience which will make this process effortless. 
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +The m365 setup command is a wizard that helps you configure the CLI for Microsoft 365 for your needs. It will ask you a series of questions and based on your answers, it will configure the CLI for Mi
```suggestion
The m365 setup command is a wizard that helps you configure the CLI for Microsoft 365 for your needs. It will ask you a series of questions and based on your answers, it will configure the CLI for Microsoft 365 for you and now it will also help you create your own Microsoft Entra app registration in a matter of seconds.
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +You can choose between using an existing Entra app or creating a new one. If you choose to create a new app, the CLI will ask you to choose between a minimal and a full set of permissions.
```suggestion
You can choose between using an existing Entra app or creating a new one. If you choose to create a new app, CLI will ask you to choose between a minimal and a full set of permissions. 
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +Minimal set of permissions will create a new Entra app registration with only `User.Read` scope. This is a perfect starting point to have a ready to use app that then you may manually modify to add o
```suggestion
A minimal set of permissions will create a new Microsoft Entra app registration with only a `User.Read` scope. This is a perfect starting point to have a ready-to-use app that you may then manually modify by adding the needed scopes for your script. 
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +Full set of permission, on the other hand, will create an Entra app registration with all the scopes currently required to run all commands CLI for Microsoft 365 has. This is very convinient and is t
```suggestion
A full set of permissions, on the other hand, will create a Microsoft Entra app registration with all the scopes currently required to run all commands CLI for Microsoft 365 has. This is very convenient and is the easiest thing to pick to get unblocked with all CLI functionalities.
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +Whats important to now is that the `setup` command signs in as Azure CLI to your tenant to creates a new app registration, and stores its information in the CLI configuration so that then you don't n
```suggestion
What's important to know is that the `setup` command signs in as Azure CLI to your tenant to create a new app registration. This information is then stored in the CLI configuration so that you don't need to specify them yourself in the `login` command. Check out how easy and convenient it is in this short demo:
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +> To help you upgrade to v9, we prepared a summary of the breaking change and the recommended actions. For more information see the [v9 Upgrade Guidance](https://pnp.github.io/cli-microsoft365/v9-upg
```suggestion
> To help you upgrade to v9, we prepared a summary of the breaking changes and the recommended actions. For more information see the [v9 Upgrade Guidance](https://pnp.github.io/cli-microsoft365/v9-upgrade-guidance/) on our docs.
```

2024-08-31 19:14 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +Following is an overview of the most noteworthy changes in v8.
Everything below is not `v8` right? They will be released together with this `v9`, right? The only difference is that these are non-breaking changes.

2024-09-01 01:12 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +This major release is a reaction to an announcement that the PnP Management Shell multi-tenant app will be removed on September 9. Previously you were able to use this app to grant the needed permiss
```suggestion
This major release is a reaction to an announcement that the PnP Management Shell multi-tenant app will be removed on September 9. Previously you were able to use this app to grant the needed permissions for your scripts or standard usage of CLI for Microsoft 365. Till now it was even used as the default login method. The removal of this approach might have an impact on your existing scripts. Check the following [recording for more details](https://www.youtube.com/watch?v=VNgc4k_gCT0) on this announcement. Although using the PnP Management Shell was very convenient it wasn't the best approach that should be picked especially when running automated scripts on your tenant. This option will now go away to help customers to improve their security posture by encouraging the use of single-tenant app and just the scopes and permissions that are needed. CLI for Microsoft 365 already supports login over your own Entra app registration and we already have [guidance that will guide you through the process](https://pnp.github.io/cli-microsoft365/user-guide/using-own-identity). In this release, we introduced some features that might prove very helpful in adapting to this change.
```

2024-09-01 01:16 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +Following is an overview of the most noteworthy changes in v8.
this is quite strange. I already updated this before your comment

2024-09-01 01:18 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
> +This major release is a reaction to an announcement that the PnP Management Shell multi-tenant app will be removed on September 9. Previously you were able to use this app to grant the needed permiss
```suggestion
This major release is a reaction to an announcement that the PnP Management Shell multi-tenant app will be removed on September 9. Previously you were able to use this app to grant the needed permissions for your scripts or standard usage of CLI for Microsoft 365. Till now it was even used as the default login method. The removal of this approach might have an impact on your existing scripts. Check the following [blog post for more details](https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/) on this announcement. Although using the PnP Management Shell was very convenient it wasn't the best approach that should be picked especially when running automated scripts on your tenant. This option will now go away to help customers to improve their security posture by encouraging the use of single-tenant app and just the scopes and permissions that are needed. CLI for Microsoft 365 already supports login over your own Entra app registration and we already have [guidance that will guide you through the process](https://pnp.github.io/cli-microsoft365/user-guide/using-own-identity). In this release, we introduced some features that might prove very helpful in adapting to this change.
```

2024-09-01 01:29 UTC, merged