Cli for Microsoft 365 release blog post v10
pnp/blog pull request #1961
Opened 2024-10-28 20:48 UTC by Adam-it

## Category

- [X] New article

2024-10-30 09:52 UTC, Jwaegebaert approved these changes
Looks very good @Adam-it. Noticed a few typos but besides that, it looks ready to go!

2024-10-30 09:52 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +We also introduced breaking changes that will greatly improve some functionalities of our product. For example, we updated the API endpoints that were used in [spo folder move](https://pnp.github.io/
```suggestion
We also introduced breaking changes that will greatly improve some functionalities of our product. For example, we updated the API endpoints that were used in [spo folder move](https://pnp.github.io/cli-microsoft365/cmd/spo/folder/folder-move/) and [spo folder copy](https://pnp.github.io/cli-microsoft365/cmd/spo/folder/folder-copy/) commands so that now it will be possible to manage large folders between site collections. As now we use different APIs we also need to adapt our command options to what is supported in the new endpoints. You may read more details about this change here: 
```

2024-10-30 09:52 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +This major release also introduce a brand new [spp model list](https://pnp.github.io/cli-microsoft365/cmd/spp/model/model-list/) command which will allow you to retrieve the list of unstructured docu
```suggestion
This major release also introduces a brand new [spp model list](https://pnp.github.io/cli-microsoft365/cmd/spp/model/model-list/) command which will allow you to retrieve the list of unstructured document processing models.
```

2024-10-30 09:52 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +or you may get the list of members by specifying the group ID by running:
```suggestion
Or you may get the list of members by specifying the group ID by running:
```

2024-10-30 09:52 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +Besides all these new commands, we've also made some changes to some existing commands. A few bugs have been fixed and the codebase has been polished. Let's have a closer look at some of the updates
```suggestion
Besides all these new commands, we've also made some changes to some existing commands. A few bugs have been fixed and the codebase has been polished. Let's have a closer look at some of the updates that stand out the most.
```

2024-10-30 09:52 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +Not so long ago we updated the default behavior of the login command which now requires you to provide an app registration which will allow CLI for Microsoft 365 to sign in to your tenant. You may re
```suggestion
Not so long ago we updated the default behavior of the login command which now requires you to provide an app registration which will allow CLI for Microsoft 365 to sign in to your tenant. You may read more details about this change in [previous major release blog post](https://pnp.github.io/blog/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/#the-new-major-version-of-cli-for-microsoft-365--v9). Along with this change we updated the `m365 setup` command so that it now also allows you to create the required app registration on your tenant along with all required settings and selected set of permissions. In this release we updated the default name of this app to 'CLI for M365', previously it was 'CLI for Microsoft 365'. Unfortunately, it turned out that the word 'Microsoft' in your app registration name blocks it from becoming multitenant. That is why in order to avoid this unnecessary problem we updated the name.
```

2024-10-30 09:52 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +title: CLI for Microsoft 365 v9
```suggestion
title: CLI for Microsoft 365 v10
```

2024-10-30 14:00 UTC, Adam-it commented
> Looks very good @Adam-it. Noticed a few typos but besides that, it looks ready to go!

thanks @Jwaegebaert for the feed. I added all your changes

2024-10-31 09:17 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +We have just published a new major version of CLI for Microsoft 365 v10. [CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsof
We mention here only one breaking change while later on there are several. I suggest we broaden the statement in the intro paragraph to more clearly communicate that there are several breaking changes.

2024-10-31 09:17 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +The usage is as always very simple and in order to retrieve a list of SharePoint Premium unstructured document processing models on the content center site, simply run:
Avoid repeating "simple" in one sentence.

2024-10-31 09:31 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +The usage is as always very simple and in order to retrieve a list of SharePoint Premium unstructured document processing models on the content center site, simply run:
done

2024-10-31 09:31 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +We have just published a new major version of CLI for Microsoft 365 v10. [CLI for Microsoft 365](https://aka.ms/cli-m365) is a cross-platform command-line tool that allows you to manage your Microsof
ajj a copy paste mistake from previous major. sorry for that

2024-10-31 09:59 UTC, milanholemans requested changes
I noticed that we are using a lot of links with anchors for the v10 upgrade guidance.
As I'm currently rewriting the upgrade guidance, there is no guarantee that these anchors will still be there. Maybe we should just reference the change without a hyperlink, or we'll have to update this release blog when the upgrade guidance has been rewritten.

2024-10-31 09:59 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +We also introduced breaking changes that will greatly improve some functionalities of our product. For example, we updated the API endpoints that were used in [spo folder move](https://pnp.github.io/
```suggestion
We also introduced breaking changes that will greatly improve some functionalities of our product. For example, we updated the API endpoints that were used in [spo folder move](https://pnp.github.io/cli-microsoft365/cmd/spo/folder/folder-move/) and [spo folder copy](https://pnp.github.io/cli-microsoft365/cmd/spo/folder/folder-copy/) commands so that now it will be possible to copy/move larger folders between site collections. As we now use different APIs we also need to adapt our command options to what is supported in the new endpoints. You may read more details about this change here: 
```

2024-10-31 09:59 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +Similar improvements we introduced to [spo file copy](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-copy/) and [spo file move](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-move
```suggestion
Similar improvements are introduced to [spo file copy](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-copy/) and [spo file move](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-move/) commands. We also updated those commands to new endpoints to ensure the command's functionality and reliability. You may find more details about those changes here: 
```

2024-10-31 09:59 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +- or we updated the purpose of option `displayName` for [entra m365group set command](https://pnp.github.io/cli-microsoft365/cmd/entra/m365group/m365group-set)
```suggestion
- updated the purpose of option `displayName` for [entra m365group set command](https://pnp.github.io/cli-microsoft365/cmd/entra/m365group/m365group-set) 
```

2024-10-31 10:54 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v10-0/index.md
> +Not so long ago we updated the default behavior of the login command which now requires you to provide an app registration which will allow CLI for Microsoft 365 to sign in to your tenant. You may re
TBH I would. Creating this app reg is a brand new thing we introduced and already has a change/update so I guess it's worth being transparent here as well

2024-10-31 11:12 UTC, Adam-it commented
> I noticed that we are using a lot of links with anchors for the v10 upgrade guidance. As I'm currently rewriting the upgrade guidance, there is no guarantee that these anchors will still be there. Maybe we should just reference the change without a hyperlink, or we'll have to update this release blog when the upgrade guidance has been rewritten.

we may update the blog post at any time. I will try to review your PR with changes in our upgrade guidance and then align it with this blog post and just create a PR with content change to this blog post.
Awesome feed 👏

2024-10-31 11:12 UTC, merged