Adds Cli for microsoft 365 2024 wrap up
pnp/blog pull request #2000
Opened 2024-12-24 09:57 UTC by Adam-it

## Category

- [x] New article

2024-12-24 16:20 UTC, milanholemans requested changes
Well done @Adam-it! Made a few remarks while reading.

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +If you are interested in the full list of changes and improvements, you can check out the [release notes](https://pnp.github.io/cli-microsoft365/v10-upgrade-guidance).
let's either point to the release notes, or refer to it as upgrade guidance.

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +Over the year we introduced many new features and improvements to the CLI for Microsoft 365 but the one that stand out most this year is the possibility to sign in to multiple accounts/tenants and th
```suggestion
Over the year we introduced many new features and improvements to the CLI for Microsoft 365 but the one that stand out the most this year is the possibility to sign in to multiple accounts/tenants and then just switch between them without the need to sign out and sign in again. This feature is especially useful for admins who manage multiple tenants, these might by dev, test, and production environments or different client tenants. This is a significant quality-of-life improvement that makes everything much easier and faster.
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +This year we introduced many new commands but we are always looking for new areas to expand our CLI for Microsoft 365. All in all the aim is to have a single CLI to manage all Microsoft 365 services.
```suggestion
This year we introduced many new commands but we are always looking for new areas to expand our CLI for Microsoft 365. All in all, the aim is to have a single CLI to manage all Microsoft 365 services. This year we introduced new commands to manage [SharePoint Premium](https://adoption.microsoft.com/en-us/sharepoint-premium/start/) and [SharePoint Embedded](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/overview).
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +Regarding SharePoint Premium we mainly introduced `m365 spp` commands that allow you to [document understanding models](https://pnp.github.io/cli-microsoft365/cmd/spp/model/model-get)
```suggestion
Regarding SharePoint Premium we mainly introduced `m365 spp` commands that allow you manage [document understanding models](https://pnp.github.io/cli-microsoft365/cmd/spp/model/model-get)
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +This year was very busy for us. To give you a better idea of how much work we have done, here are some numbers:
```suggestion
This year was very busy for us. To give you a better idea of the extent of our work, here are some numbers:
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +## Work done in numbers
@waldekmastykarz is it possible to share any usage stats?

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +This year is special as we are celebrating the 100th release of CLI for Microsoft 365. Over the years, we’ve continually worked to enhance your experience, expand our capabilities, and keep pace with
```suggestion
This year is special as we are celebrating the 100th release of CLI for Microsoft 365. Over the years, enhanced your experience, expanded our capabilities, and kept pace with the evolving Microsoft 365 ecosystem.
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +Reaching this milestone is a testament to the amazing contributions of our community, the dedication of our team, and the ongoing support of our users. Thank you for being part of this journey—we’re
```suggestion
Reaching this milestone is a testament to our community's contributions, our team's dedication, and our users' ongoing support. Thank you for being part of this journey—we’re excited to continue building a brighter future together!
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +We value your feedback and are eager to hear from you. If you have any suggestions for improvement or want to engage with our community, you can reach out to us on [GitHub](https://github.com/pnp/cli
```suggestion
We value your feedback and are eager to hear from you. If you have any suggestions for improvement or want to engage with our community, you can reach out to us on [GitHub](https://github.com/pnp/cli-microsoft365/issues), [Discord](https://aka.ms/cli-m365/discord), or [Bluesky](https://bsky.app/profile/climicrosoft365.bsky.social). Don't hesitate to connect with us, as your input plays a vital role in shaping the future of CLI for Microsoft 365.
```

2024-12-24 16:20 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +- [Join the Microsoft 365 & Power Platform Community Discord Server](https://discord.gg/YtYrav2VGW)
```suggestion
- [Join the Microsoft 365 & Power Platform Community Discord Server](https://aka.ms/cli-m365/discord)
```

2024-12-25 21:32 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-2024-wrap-up/index.md
> +## Work done in numbers
I added some basic info about our highest npm package download with link to stats from what we share on GH discussions

2024-12-25 21:33 UTC, merged