Added Q&A and some minor fixes
pnp/blog pull request #207
Opened 2022-05-16 17:44 UTC by davidchesnut

## Category

- [ x] Content fix
- [ ] New article

## Contents of the Pull Request

Adding Q&A for the May 2022 blog for Office Add-ins

2022-05-16 22:57 UTC, lindalu-MSFT requested changes
Hi @davidchesnut, made some changes for voice and clarity. A few errant hyphens got in here, too, but I blame it on Word autocorrect! LMK if you have questions. A few places I requested verification if I changed meaning or not.

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +**I'd love to follow-up on this feature request: [Office JS Save and Close methods for Word, Excel, and PowerPoint](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-s
```suggestion
**I'd love to follow-up on this feature request: [Office JS Save and Close methods for Word, Excel, and PowerPoint](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-save-and-close-methods-for-word-excel-and-powerpoint/idi-p/2800214). Apologies for my persistence, but this is literally the only blocking issue for us to move from the old add-ins to the Office web Add-ins platform. We would really appreciate if you could push this into the roadmap. We represent hundreds of users and the deployments of the old add-ins and updates are not ideal. Thank you so much.**
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +Thanks for your persistence! We're sorry you are being blocked by this. Unfortunately we can't add this to the roadmap at this time, but we will continue to keep an eye on the request.
```suggestion
Thanks for your persistence! We're sorry you're blocked by this. Unfortunately, we can't add this to the roadmap at this time, but we'll continue to keep an eye on the request. Consider asking the [Office JS developer community](https://stackoverflow.com/questions/tagged/office-js) on Stack Overflow how others have addressed this issue.
```
Consider updating the question on TechCommunity, too!

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +As a workaround you may want to explore continuing to use your COM add-in for full functionality while adding partial functionality in the web add-in for cross-platform support. We recommend explorin
```suggestion
As a workaround you may want to explore continuing to use your COM add-in for full functionality while adding partial functionality in the web add-in for cross-platform support. For more information, we recommend exploring [Make your Office Add-in compatible with an existing COM add-in](https://docs.microsoft.com/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in).
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +We'd like to know more about this scenario. Can you please create a feature request with more information at https://aka.ms/m365dev-suggestions? Thanks!
```suggestion
We'd like to know more about this scenario. Can you please create a feature request with more information at [https://aka.ms/m365dev-suggestions](https://aka.ms/m365dev-suggestions)? Thanks!
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +We see this question was also [posted to the Q&A site](https://docs.microsoft.com/answers/questions/827167/how-to-call-office-js-function-hosted-in-taskpane.html). It seems like you should be able to
```suggestion
We see this question was also [posted to the Q&A site](https://docs.microsoft.com/answers/questions/827167/how-to-call-office-js-function-hosted-in-taskpane.html). You should be able to use the [onSelectionChanged](https://docs.microsoft.com/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-onselectionchanged-member) event. If not, can you please follow up with more information on the Q&A site? Thanks!
```
Is this more like an issue? Should we point them to office-js repo instead?

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +**During the last call, one of my questions was if it would be possible to programmatically let the compose window disappear after the user clicked on a custom "Encrypt and Send" button, as the mail
```suggestion
**During the last call, one of my questions was is possible to programmatically let the compose window disappear after the user clicks a custom "Encrypt and Send" button, as the mail already is encrypted. Then send the email as a MIME payload via the send message Graph API. You suggested to use smart alerts to handle the send event. However, this is not ideal for our use case. The on-send event is triggered on each email, but we want the user to deliberately decide via the custom button if they want to encrypt the email or not. Also, encrypting "on the fly" via OnMessage events is not on option as not every mail should be encrypted. Also, it does not work well with our custom encryption protocol. Hence, a feature request could be to programmatically discard the current composed mail, and subsequently close the compose form.**
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +We are not planning to override or suppress the native send button, nor to expose a cancel composition API This can cause user confusion, and could be used maliciously in some conditions. The scenari
```suggestion
We are not planning to override or suppress the native send button, nor to expose a cancel composition API. This can cause user confusion and could be used maliciously in some conditions. The scenario can still be solved with smart alerts. The key here is to combine the following things.
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +Pre-conditions: we cannot override the “send” button in Outlook. This is also not a recommended experience for Outlook users who expect to send an item using the native “send” option. So the ability
```suggestion
Pre-conditions: we cannot override the “send” button in Outlook. This is also not a recommended experience for Outlook users who expect to send an item using the native “send” option. So, the ability to encrypt and send UEX-wise is not possible.
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +1. Indeed the user needs to take an explicit action to encrypt the content. So there needs to be an “Encrypt Message” button. The button needs to open a task pane and ask the user what they want to e
```suggestion
1. Indeed the user needs to take an explicit action to encrypt the content. So there needs to be an “Encrypt Message” button. The button needs to open a task pane and ask the user what they want to encrypt (should the add-in encrypt the message? the attachments? all?) Also, the task pane can configure other settings or rules. For example, a rule like “always encrypt when sending messages to this particular customer”. Those can be stored as a mailbox setting, so that afterwards the setting can be honored when running the on-send event.
```
This is good info. Is this a scenario you can add to the [on-send documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows)? Also, we apparently refer to these events collectively as "on-send" and only .OnSend when part of the actual event/method/property. Suggest changing references to on-send for consistency! (Or choose one or the other.)

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +4. You can also avoid a heavy onSend management logic if you encrypt attachments as they are added using the attachment added event.
```suggestion
4. To avoid a heavy onSend management logic, consider encrypting attachments as they are added using the AttachmentAdd event.
```
Consider including the link to the documentation.

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +**Are you planning on upgrading the Visual Studio Web Add-in Templates to Asp.Net Core?**
```suggestion
**Do you plant to upgrade the Visual Studio Web Add-in templates to ASP.NET Core?**
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +We are looking into some updates to the Visual Studio Office Add-in templates, but don't have anything on the roadmap at this time. Can you let us know more about what you'd like to see in these temp
```suggestion
We are looking into some updates to the Visual Studio Office Add-in templates, but don't have anything on the roadmap at this time. Please let us know more about what you'd like to see in these templates by posting a request at [https://aka.ms/m365dev-suggestions](https://aka.ms/m365dev-suggestions).
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +**If the task pane is specified in the add in manifest.xml that is installed by an admin, it will always show in Excel files. Is there a way for Excel add-ins that are installed by an admin, to appea
```suggestion
**If the task pane is specified in the add in manifest.xml that is installed by an admin, it will always show in Excel files. Is there a way for Excel add-ins that are installed by an admin to appear for a user or group only when the Excel file is created by the SaaS application, and not for existing or new Excel files created by the user?**
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +Once an add-in is deployed and it has **Show Taskpane** commands, those commands will appear in all Excel workbooks. You might be able to hide a custom tab if certain properties on the workbook are p
```suggestion
The **Show Taskpane** commands appear in all Excel workbooks once an add-in is deployed. To hide a custom tab, certain properties on the workbook must be present. See the [visible property](https://docs.microsoft.com/javascript/api/office/office.tab?view=common-js-preview#office-office-tab-visible-member) for more information.
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +Thanks for pinging us on this. It could be that the PowerShell command is actually using the store validation that ACCEPTS launch event annotations, so this is probably failing erroneously. We'll inv
```suggestion
Thanks for pinging us on this. It's possible that the PowerShell command is using the store validation that ACCEPTS launch event annotations causing it to fail erroneously. We'll investigate more and follow up on the original GitHub issue.
```
Consider adding the link to the original GitHub.

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +This should not be the case, this could happen within 72 hours in the worst case. There are a few conditions (depending on the type of add-in) that requires an admin to approve the update (i.e. if yo
```suggestion
This should not be the case; this could happen within 72 hours in the worst case. Depending on the type of add-in, there are a few conditions that require an admin to approve the update (i.e. if your add-in was updated to support SSO, or event-based in Outlook). If you can provide more details we can definitely help you (what type of add-in is this). Please let us know more at [office-js on Stack Overflow](https://stackoverflow.com) or the [Q&A forum](https://aka.ms/office-addins-dev-questions).
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +When these commands are invoked, we start the runtime that is required to execute the action. This may result in a bit of a delay that you are experiencing. One way to work around this issue is to us
```suggestion
When these commands are invoked, we start the runtime that is required to execute the action. This may result in the delay that you are experiencing. A work around is to use the shared runtime in your add-in. The shared runtime starts the same runtime as the task pane and it continues to run in the background even when the task pane is closed. This avoids having to start the runtime every time a ribbon button is invoked for an action. For more information, see [Configure your Office Add-in to use a shared JavaScript runtime](https://docs.microsoft.com/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime).
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +You can ask any technical question you need help with. We monitor both https://stackoverflow.com and the [Q&A forum](https://aka.ms/office-addins-dev-questions).
```suggestion
You can ask any technical question you need help with. We monitor both [office-js questions on Stack Overflow](https://stackoverflow.com) and the [Q&A forum](https://aka.ms/office-addins-dev-questions).
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +We're investigating this. We ideally want to allow the same operations that we allow on EWS (like 14 services). But there's a lot of complexity to solve to allow this. We'll let you know down the roa
```suggestion
We're investigating this. Ideally, we want to allow the same operations that we allow on Exchange Web Services (EWS). But there's a lot of complexity to solve to allow this. We'll let you know if we have updates. In the meantime, the recommended flow is that the server should get the Graph token using the [OAuth 2.0 On-Behalf-Of flow (OBO)](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow).
```
What are "14 services?"

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +In the case of mobile the alternative is to use EWS. You can also request an exception at https://aka.ms/RESTCheck that also applies to mobile. If your add-in is using REST before the November 2022 d
```suggestion
For mobile, the alternative is to use Exchange Web Services (EWS). You can also request an exception at https://aka.ms/RESTCheck that also applies to mobile. If your add-in is using REST before the November 2022 decommission date, it will be allowed to work until we end support for Office 2019.
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
> +    * Documentation - [Test your Office Add-in on Internet Explorer](https://docs.microsoft.com/office/dev/add-ins/testing/ie-11-testing)
```suggestion
    * Documentation – [Test your Office Add-in on Internet Explorer](https://docs.microsoft.com/office/dev/add-ins/testing/ie-11-testing)
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
>      * Documentation - [Microsoft AppSource submission FAQ](https://docs.microsoft.com/office/dev/store/appsource-submission-faq)
```suggestion
    * Documentation – [Microsoft AppSource submission FAQ](https://docs.microsoft.com/office/dev/store/appsource-submission-faq)
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
>      * Forum - [Microsoft Ideas forum - Feedback Portal](https://feedbackportal.microsoft.com/feedback)
```suggestion
    * Forum – [Microsoft 365 Developer Ideas forum](https://feedbackportal.microsoft.com/feedback)
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
>      * Issues - [OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues)
```suggestion
    * Issues – [OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues)
```

2022-05-16 22:57 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-05-11/index.md
>      * Forum - [Microsoft Ideas forum - Feedback Portal](https://feedbackportal.microsoft.com/feedback)
For SEO, please consider adding the following at the bottom:
**Additional Resources**
[Microsoft 365 Developer Program](https://aka.ms/m365/devprogram)
[Microsoft 365 Dev Center](https://developer.microsoft.com/microsoft-365)

2022-05-17 09:43 UTC, LuiseFreese commented
Hey @davidchesnut - I added you as a maintainer to this repo - you should be able to merge (your own) PRs. Let me know if you need any support - here and happy to help :-)

2022-05-18 03:48 UTC, davidchesnut commented
> Hey @davidchesnut - I added you as a maintainer to this repo - you should be able to merge (your own) PRs. Let me know if you need any support - here and happy to help :-)

Super helpful! Thank you @LuiseFreese !

2022-05-18 18:31 UTC, merged