New article
pnp/blog pull request #286
Opened 2022-06-03 14:43 UTC by Favour-dgreat

## Category

- [x] New article

## Contents of the Pull Request

> New article on Microsoft Power Pages

2022-06-04 18:32 UTC, hugoabernier requested changes
These changes should be reverted. Please make sure that you only affect the files related to your post.

2022-06-04 18:35 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +# Connecting to Microsoft Dataverse
You should only have one level 1 heading in the post, and it is reserved for the page title. Please stick to level 2 (`##`) or above.

2022-06-04 18:43 UTC, hugoabernier requested changes
Great article, only need to fix a few accessibility issues and mardown issues. Also, please revert changes that are not related to your post (see the other commits in this pull request)

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![banner.webp](images/banner.webp)
The alt tag should describe the image

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +# What are Data Connectors?
Level one headings are not allowed

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![image1.png](images/image1.png)
Descriptive alt tag required

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![image2.png](images/image2.png)
Descriptive alt tag required

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![image3.png](images/image3.png)
Descriptive alt tag required

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![image4.png](images/image4.png)
Descriptive alt tag required

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![image5.png](images/image5.png)
Descriptive alt tag required

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +![image6.png](images/image6.png)
Descriptive alt tag required

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +1. [Overview of connectors for canvas apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list)
Please remove `/en-us/` from URLs so the links are relevant for non-US visitors

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +2. [Use custom connectors in a Power Apps canvas app](https://docs.microsoft.com/en-us/learn/modules/use-custom-connectors-in-powerapps-canvas-app/)
No `/en-us/` please

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +The image above showing popular connectors are all Standard Connectors.
Please avoid terms like `above` for accessibility reasons.

2022-06-04 18:43 UTC, hugoabernier commented on content/post/understanding-data-connectors-with-microsoft-power-apps/index.md
> +Check out this article for more on  Custom Connectors - [Register and use custom connectors](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/register-custom-api)
No `en-us` in URLs please

2022-06-06 10:02 UTC, Favour-dgreat commented
I have made necessary adjustments.

2022-06-07 15:13 UTC, closed without merging

2022-06-08 04:52 UTC, hugoabernier commented
> Oh thank You so much. Is it live on the community blog now?
 Yes, sorry, I should have been clearer! Thank you for your article!

2022-06-08 18:04 UTC, Favour-dgreat commented
I could only find the previously published article. The other article I
sent in have not been published yet?
On Wed, 8 Jun 2022 at 05:52, Hugo Bernier ***@***.***> wrote:

> Oh thank You so much. Is it live on the community blog now?
> Yes, sorry, I should have been clearer! Thank you for your article!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pnp/blog/pull/286#issuecomment-1149459060>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMUQ2T2J6PJXFFGGDQD3QODVOARIVANCNFSM5XZHHP2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-08 21:19 UTC, Favour-dgreat commented
The second article the one that talked on Power Pages
On Wed, 8 Jun 2022 at 22:18, Hugo Bernier ***@***.***> wrote:

> I'm sorry, the pull request touched every single article in the blog,
> which made it difficult to guess which article was updated. If you tell me
> which article you mean to submit, I'll go manually merge it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pnp/blog/pull/286#issuecomment-1150425032>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMUQ2TZZX7ER3ZDXPO4YJZLVOEE3PANCNFSM5XZHHP2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-08 21:21 UTC, hugoabernier commented
Can you give me the article name or slug?

2022-06-08 21:22 UTC, Favour-dgreat commented
Quick Overview of Microsoft Power Pages - that’s the title

On Wed, 8 Jun 2022 at 22:21, Hugo Bernier ***@***.***> wrote:

> Can you give me the article name or slug?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pnp/blog/pull/286#issuecomment-1150427013>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMUQ2TYV27VDERTSKIZ3YY3VOEFEXANCNFSM5XZHHP2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-08 22:34 UTC, hugoabernier commented
Ok, I merged the article. Please try to keep your pull requests to a single article in your future pull requests so we can process them without further issues.