[Office Add-ins] Create blog post for June community call
pnp/blog pull request #321
Opened 2022-06-13 23:24 UTC by samantharamon

## Category

- [ ] Content fix
- [X] New article

## Related issues

N/A

## Contents of the Pull Request

Blog post for the Office Add-ins June community call.

## Guidance

None

2022-06-13 23:36 UTC, davidchesnut approved these changes
One small URL change, otherwise looks great!

2022-06-13 23:36 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Give us feedback on what you need from code samples. Join the Teams call – [Office Add-ins samples discussion](https://aka.ms/officeaddinsamples-call) – June 15, 8:00 AM PT \| <https://aka.ms/offic
```suggestion
* Give us feedback on what you need from code samples. Join the Teams call – [Office Add-ins samples discussion](https://aka.ms/officeaddinsamples-join) – June 15, 8:00 AM PT \| <https://aka.ms/officeaddinsamples-call>
```

Updating with link to the calendar invite.

2022-06-14 15:27 UTC, lindalu-MSFT commented
@samantharamon Is there a preview link I can look at?

2022-06-14 16:16 UTC, lindalu-MSFT requested changes

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* See the full blog post for this call in the Microsoft 365 platform community blog – <https://aka.ms/m365pnp/blog>
```suggestion
* See the full blog post for this call in the [Microsoft 365 platform community blog](https://aka.ms/m365pnp/blog)
```
For SEO, suggest you make these actual links for search engines to crawl the link text for keywords.

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Twitter – <https://twitter.com/microsoft365dev>
```suggestion
* Follow us on [Twitter](https://twitter.com/microsoft365dev)
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Microsoft 365 Platform Community in YouTube – <https://aka.ms/m365/videos>
```suggestion
* [Microsoft 365 Platform Community on YouTube](https://aka.ms/m365/videos)
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Link to all Microsoft Developer Community calls – <https://aka.ms/M365DevCalls>
```suggestion
* All [Microsoft Developer Community calls](https://aka.ms/M365DevCalls)
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Submit questions for next community call – <https://aka.ms/officeaddinsform>
```suggestion
* [Submit questions about add-ins development](https://aka.ms/officeaddinsform) for our next community call
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Next community call – July 13th at 8:00 AM PT – <https://aka.ms/officeaddinscommunitycall>
```suggestion
* Next community call – July 13th at 8:00 AM PT – [Add to calendar](https://aka.ms/officeaddinscommunitycall)
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* Sign up for the PnP Recognition Program and earn contribution badges – <https://pnp.github.io/recognitionprogram/>
```suggestion
* [Sign up for the PnP Recognition Program](https://pnp.github.io/recognitionprogram/) and earn contribution badges
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +The call was hosted by [David Chesnut](http://twitter.com/davidchesnut) (Microsoft) \| @davidchesnut. Recorded June 8, 2022.
```suggestion
The call was hosted by [David Chesnut](http://twitter.com/davidchesnut) (Microsoft) | @davidchesnut. Recorded June 8, 2022.
```

2022-06-14 16:16 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-06-08/index.md
> +categories: ["Office add-in developer community call"]
```suggestion
categories: ["Office Add-in developer community call"]
```

2022-06-14 17:44 UTC, samantharamon commented on content/office-add-ins-community-call/2022-06-08/index.md
> +* **Using Blazor in a Microsoft Excel add-in** – Step through creating a Blazor Webassembly Excel add-in – [Maarten van Stam](http://twitter.com/aafvstam) – MVP Office Add-ins \| @aafvstam
I initially thought this was used to escape the pipe character in Markdown, but it looks like we don't need to do this for it. Committing your suggestion.

2022-06-14 19:18 UTC, samantharamon commented
> @samantharamon Is there a preview link I can look at?

Unfortunately, there doesn't appear to be a way to preview the content as it would appear on the blog. For now, this is the best way to preview the content in GitHub: https://github.com/pnp/blog/blob/084760a0bdd9591a3339ed8116abedb5d50a2582/content/office-add-ins-community-call/2022-06-08/index.md

2022-06-14 19:54 UTC, lindalu-MSFT approved these changes

2022-06-14 19:54 UTC, lindalu-MSFT commented
@samantharamon Approved!

2022-06-14 20:01 UTC, merged