July 13 Office Add-ins Community Call Q&A Post
pnp/blog pull request #465
Opened 2022-07-22 22:56 UTC by preethikakiru

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

> This PR adds the Questions and Answers from the previous add-in community call on July 13th. This content is currently a draft, after approval I will change the draft value to false.

2022-07-23 03:59 UTC, samantharamon reviewed
@preethikakiru, thank you again for creating this month's post. It looks great! I added some suggestions for your consideration. Please also add the July call slide deck to the 'files' folder. Thanks!

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* **SSO samples update** – SSO NodeJS sample token handling has been updated – learn what and why – [David Chesnut] - Senior Technical Writer (Microsoft) | @davidchesnut
```suggestion
* **SSO samples update** – Learn about updates to the SSO NodeJS token handling sample and how you can retrieve an access token securely – [David Chesnut](http://twitter.com/davidchesnut) – Senior Technical Writer (Microsoft) | @davidchesnut
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Give us feedback on what you need from code samples. Join the Teams call – [Office Add-ins samples discussion](https://aka.ms/officeaddinsamples-join) – July 27th, 8:00 AM PT \| <https://aka.ms/off
@davidchesnut I remember you made changes to the invite. Does aka.ms/officeaddinsamples-join still work?

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Word update – [Yun Wang] - Principal Product Manager (Microsoft) – [1:21](https://www.youtube.com/watch?v=COic6ghBWsU&t=81s)
```suggestion
* Word API update – Yun Wang – Principal Product Manager (Microsoft) – [1:21](https://www.youtube.com/watch?v=COic6ghBWsU&t=81s)
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Outlook Add-ins Update – [Juan Balmori] - Principal Product Manager (Microsoft) | @juaneloBalmor & - [Victoria Iannotti] - Software Engineer (Microsoft) – [6:11](https://www.youtube.com/watch?v=COi
```suggestion
* Outlook add-ins update – [Juan Balmori](http://twitter.com/juaneloBalmori) – Principal Product Manager (Microsoft) | @juaneloBalmor and [Victoria Iannotti](https://www.linkedin.com/in/victoria-iannotti/) – Software Engineer (Microsoft) – [6:11](https://www.youtube.com/watch?v=COic6ghBWsU&t=371s) 
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* SSO samples update – [David Chesnut] - Senior Technical Writer (Microsoft) | @davidchesnut – [23:38] (https://www.youtube.com/watch?v=COic6ghBWsU&t=1418s)
```suggestion
* SSO samples update – [David Chesnut] (http://twitter.com/davidchesnut) – Senior Technical Writer (Microsoft) | @davidchesnut – [23:38] (https://www.youtube.com/watch?v=COic6ghBWsU&t=1418s)
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Q&A – (http://twitter.com/davidchesnut) – Senior Technical Writer (Microsoft) \| @davidchesnut – [44:34](https://www.youtube.com/watch?v=COic6ghBWsU&t=2674s)
```suggestion
* Q&A – [David Chesnut](http://twitter.com/davidchesnut) – Senior Technical Writer (Microsoft) \| @davidchesnut – [44:34](https://www.youtube.com/watch?v=COic6ghBWsU&t=2674s)
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* [Join the next community call](https://aka.ms/officeaddinscommunitycall) on July 13th at 8:00 AM Pacific Time (PT)
```suggestion
* [Join the next community call](https://aka.ms/officeaddinscommunitycall) on August 10th at 8:00 AM Pacific Time (PT)
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +If you are referring to keyboard shortcuts, yes, but this is only available in Excel today. You can find more information in https://docs.microsoft.com/office/dev/add-ins/design/keyboard-shortcuts. I
```suggestion
If you're referring to keyboard shortcuts, yes, but this is only available in Excel today. You can find more information in [Add custom keyboard shortcuts to your Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/design/keyboard-shortcuts). If you're looking for keyboard shortcut support in Word, please let us know more about your scenario in a feature request at https://aka.ms/m365dev-suggestions.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +(1) Can you clarify which namespace we should be using to access the getAccessToken method please ?
```suggestion
(1) Can you clarify which namespace we should be using to access the getAccessToken method please?
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +(2) Why does the documentation refer to "Office.auth" when the full namespace is "Office.context.auth" ?
```suggestion
(2) Why does the documentation refer to "Office.auth" when the full namespace is "Office.context.auth"?
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +1. You can use either namespace. They call the same code as one just maps to the other. However, for consistency throughout the docs and samples, we are updating to always use Office.auth.getAccessto
```suggestion
1. You can use either namespace. They call the same code as one just maps to the other. However, for consistency throughout the docs and samples, we're updating to always use Office.auth.getAccesstoken. It's possible that if a change were made in the future (like adding a new method) it may not appear on the original OfficeRuntime namespace. However, any code using OfficeRuntime will not break. So if you are already using OfficeRuntime, you don't need to rewrite your code.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +It isn't possible to conditionally install an add-in based on various conditions about the opened file. You can however enable functionality in your add-in based on the conditions you want to detect.
```suggestion
It isn't possible to conditionally install an add-in based on various conditions about the opened file. You can however enable functionality in your add-in based on the conditions you want to detect. For more information, see [Run code in your Office Add-in when the document opens](https://docs.microsoft.com/office/dev/add-ins/develop/run-code-on-document-open). You can also show the task pane or hide the task pane based on conditions you define. For more information, see [Show or hide the task pane of your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/develop/show-hide-add-in). You can also embed your add-in into an Excel spreadsheet if opening the file from your service. For more information, see [Open Excel from your web page and embed your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/excel/pnp-open-in-excel).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +**While we are waiting; we are considering dropping support for our COM addin for 32-bit Office; do you have any data, what percentage of users is still using 32-bit office, as opposed to 64-bit offi
```suggestion
**While we are waiting; we are considering dropping support for our COM addin for 32-bit Office; do you have any data, what percentage of users is still using 32-bit office, as opposed to 64-bit office (say since Excel 2013...)?
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We unfortunately cannot disclose user information regarding bitness. That being said for a modern add-in the users using 32 bit office may not make a heavy impact.
```suggestion
We unfortunately can't disclose user information regarding bitness. That being said, for a modern add-in, the users using 32-bit Office may not make a heavy impact. 
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We would love to get more context on the type of support you are looking for. Please contact prateek.sharma@microsoft.com.
```suggestion
We'd love to get more context on the type of support you're looking for. Please contact prateek.sharma@microsoft.com.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +By the end of this year or early next year. We encourage you to try this feature on the online version first, then have your users try it in production before the features is supported on all platfor
```suggestion
By the end of this year or early next year. We encourage you to try this feature on the online version first, then have your users try it in production before the features is supported on all platforms. To see a demo of this feature, see [Office Add-ins community call – February 9, 2022](https://pnp.github.io/blog/office-add-ins-community-call/office-add-ins-community-call-february-9-2022).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +Yes, we are looking to unify these concepts for Office.js.
```suggestion
Yes, we're looking to unify these concepts for Office.js.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +Using the Node.js environment to create your add-in could help. For further guidance with setting up your environment, see Set up your development environment - Office Add-ins | Microsoft Docs.
```suggestion
Using the Node.js environment to create your add-in could help. For further guidance with setting up your environment, see [Set up your development environment](https://docs.microsoft.com/office/dev/add-ins/overview/set-up-your-dev-environment).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +Yes, you can embed add-ins in an Excel workbook. For guidance, see Open Excel from your web page and embed your Office Add-in.
```suggestion
Yes, you can embed add-ins in an Excel workbook. For guidance, see [Open Excel from your web page and embed your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/excel/pnp-open-in-excel).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +For the technique to embed an add-in Excel using open in Teams approach, see Office-Add-in-samples/Samples/excel-open-in-teams at main · OfficeDev/Office-Add-in-samples (github.com).
```suggestion
For the technique to embed an add-in Excel using open in Teams approach, see the [Office Add-ins sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-open-in-teams).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We currently do not have concrete plans on the roadmap. It would be great if you could create a feature request with more information at https://aka.ms/m365dev-suggestions.
```suggestion
We currently don't have concrete plans on the roadmap. It would be great if you could create a feature request with more information at https://aka.ms/m365dev-suggestions.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +For any products please create an issue at:
```suggestion
For any product bugs or issues, please open a [GitHub issue](https://github.com/OfficeDev/office-js/issues/new/choose).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +https://github.com/OfficeDev/office-js
```suggestion

```
Suggesting to consolidate with previous line.

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We encourage the users to try and test the current preview APIs and provide us the feedbacks. If the users have specific requirements other than those listed in the preview, they need to go to where
```suggestion

We encourage you to try and test the current preview APIs and provide us with your feedback. If you have specific requirements other than those listed in the preview, please submit your request at https://aka.ms/m365dev-suggestions.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We would love to discuss your use case with you further. Please contact Yun Wang at wyun@microsoft.com.
```suggestion
We'd love to discuss your use case with you further. Please contact Yun Wang at wyun@microsoft.com.
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +There will be more content control support going forward, but there are currently no production plans for it this year. However, we would like to further discuss your use case with you to help us rep
```suggestion
There will be more content control support going forward, but there are currently no production plans for it this year. However, we'd like to further discuss your use case with you to help us reprioritize and see if we could push forward for another release. Please contact Yun Wang (wyun@microsoft.com) and Maja Damjanic (maja.damjanic@microsoft.com).
```

2022-07-23 03:59 UTC, samantharamon commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We currently don't have this on our list. However, we would love to know more about your use case to help us understand. Please connect with Yung Wang at wyun@microsoft.com.
```suggestion
We currently don't have this on our list. However, we'd love to know more about your use case to help us understand. Please connect with Yung Wang at wyun@microsoft.com.
```

2022-08-02 03:42 UTC, lindalu-MSFT requested changes

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* **SSO samples update** – token handling in SSO NodeJS sample has been updated to not return a middle-tier token back to the client.   Step through the logic of the three scenarios addressed in this
```suggestion
* **SSO samples update** – token handling in SSO NodeJS sample has been updated to not return a middle-tier token back to the client. Step through the logic of the three scenarios addressed in this sample: SSO with OBO (successful flow), SSO fails, must use MSAL (fallback flow), and the SSO token expired flow. Tips on extending this sample along with security notes.
```
This looks like four scenarios addressed in the sample. Also, is this just one update? Or does it need to be numbered like the previous topics?

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Q&A – (http://twitter.com/davidchesnut) – Senior Technical Writer (Microsoft) \| @davidchesnut – [44:34](https://www.youtube.com/watch?v=COic6ghBWsU&t=2674s)
I think we discussed this before, and I can't remember how we resolved. I said I didn't think we needed the backslash before the pipe. Did you verify?

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Q&A – (http://twitter.com/davidchesnut) – Senior Technical Writer (Microsoft) \| @davidchesnut – [44:34](https://www.youtube.com/watch?v=COic6ghBWsU&t=2674s)
Also, why is Agenda section after the Summaries section?

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +we have a Web Addin as well, which is backed/interacts with a server, but we are not yet in a position to completely switch away from COM; we use 3rd party DLLs, which are getting harder and harder t
```suggestion
We have a web add-in as well, which is backed/interacts with a server, but we are not yet in a position to completely switch away from COM; we use 3rd party DLLs, which are getting harder and harder to come by in 32-bit format.**
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We'd love to get more context on the type of support you are looking for. Please go submit a feature request at https://aka.ms/m365dev-suggestions.
Wouldn't this be better sent to github issues? It is not a feature request.

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +**I sent this question a few weeks ago. Any chance you can include a compare API? Basically sending 2 files to Word Online to make a comparison and see the compared file.**
```suggestion
**I sent this question a few weeks ago. Any chance you can include a compare API? Basically, sending two files to Word on the web to make a comparison and see the compared file.**
```
I know this is a customer question, which I usually leave "as is" unless it needs obvious clarification, but we should still fix any branding issues in customers' questions.

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We'd love to discuss your use case with you further. Please contact Yun Wang at wyun@microsoft.com.
We don't give out individual emails. Is there a group email or can you send them to github for support?
```suggestion
We'd love to discuss your use case with you further. 
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +There will be more content control support going forward, but there are currently no production plans for it this year. However, we'd like to further discuss your use case with you to help us reprior
```suggestion
There will be more content control support going forward, but there are currently no production plans for it this year. However, we'd like to further discuss your use case with you to help us reprioritize and see if we could push forward for another release. 
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +This is coming soon for Word. To discuss your use case further, please connect with Yung Wang at wyun@microsoft.com.
```suggestion
This is coming soon for Word.
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +By the end of this year or early next year. We encourage you to try this feature on the online version first, then have your users try it in production before the features is supported on all platfor
```suggestion
We are targeting the end of this year or early next year. We encourage you to try this feature on the online version first, then have your users try it in production before the features is supported on all platforms. To see a demo of this feature, see Office Add-ins community call – February 9, 2022 (pnp.github.io).
```
We don't make finite promises on release dates.

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +Public folders should be supported. We invite you to try out this feature in beta and welcome your feedback.
```suggestion
Public folders are supported. We invite you to try out this feature in beta and welcome your feedback.
```
Avoid ambiguity. If they are supported, say "public folders are supported". If they are not supported, say "public folders are not supported."

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We currently don't have this on our list. However, we'd love to know more about your use case to help us understand. Please connect with Yung Wang at wyun@microsoft.com.
```suggestion
We currently don't have this on our list. However, we'd love to know more about your use case to help us understand.
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +**Via the GraphAPI it is possible to add an attachment to an email object (https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=http), however, I cannot specif
```suggestion
**Via the Microsoft Graph API, it is possible to add an attachment to an email object (https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=http), however, I cannot specify metadata such as Content-Type, name, or Content-Transfer-Encoding. Will it be supported in the future or is there another way to add this information?**
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* See the full blog post for this call in the Microsoft 365 platform community blog – <https://aka.ms/m365pnp/blog>
I think I brought this up before, and maybe even corrected it in the previous post. To optimise SEO, these links should all be link text plus hot link. Google crawls link text! For example:
```suggestion
* See the full blog post at [Microsoft 365 platform community blog](https://aka.ms/m365pnp/blog)
```
Please fix the links in this section and create anchor text with a hotlink.

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +## Call Summary
```suggestion
## Call summary
```

2022-08-02 03:42 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +This month's community call topics:
```suggestion
```
This phrase redundant to the heading.

2022-08-08 22:03 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We currently don't have this on our list. However, we'd love to know more about your use case to help us understand. Please connect with Yung Wang at wyun@microsoft.com.
Yun requested for us to share his contact information with this customer.

2022-08-08 22:12 UTC, lindalu-MSFT commented
OK, just wanted to flag it. Historically, we didn't share our individual corporate emails publicly, but it this day and age of LinkedIn, etc. I think it's fine as long as Yung is fine with it.

2022-08-09 21:57 UTC, davidchesnut approved these changes
Looks good, but please take a look at Linda's feedback. Thanks!

2022-08-09 21:57 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Give us feedback on what you need from code samples. Join the Teams call – [Office Add-ins samples discussion](https://aka.ms/officeaddinsamples-join) – July 27th, 8:00 AM PT \| <https://aka.ms/off
Yes, they both work, although the call has already happened.

2022-08-09 21:57 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We'd love to get more context on the type of support you are looking for. Please go submit a feature request at https://aka.ms/m365dev-suggestions.
Yeah, this is probably a roadmap question. Like is are Visio add-ins on our radar right now, or not?

2022-08-09 22:08 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* See the full blog post for this call in the Microsoft 365 platform community blog – <https://aka.ms/m365pnp/blog>
Thanks for letting me know, I went and changed them!

2022-08-09 23:47 UTC, lindalu-MSFT approved these changes

2022-08-10 20:35 UTC, lindalu-MSFT submitted a review, later dismissed

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +**
```suggestion
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +and not Office.auth.getAccessToken
```suggestion
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +Office.context.auth.getAccessToken
```suggestion
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +1. You can use either namespace. They call the same code as one just maps to the other. However, for consistency throughout the docs and samples, we're updating to always use Office.auth.getAccesstok
```suggestion
1. You can use either namespace. They call the same code as one just maps to the other. However, for consistency throughout the docs and samples, we're updating to always use **Office.auth.getAccesstoken**. It's possible that if a change were made in the future (like adding a new method) it may not appear on the original OfficeRuntime namespace. However, any code using OfficeRuntime will not break. So, if you're already using OfficeRuntime, you don't need to rewrite your code.
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +2. The correct namespace is Office.auth.getAccessToken.
Add link to this namespace in docs

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +**While we're waiting; we're considering dropping support for our COM add-in for 32-bit Office; do you have any data, what percentage of users is still using 32-bit Office, as opposed to 64-bit Offic
```suggestion
**We're considering dropping support for our COM add-in for 32-bit Office; do you have any data, what percentage of users is still using 32-bit Office, as opposed to 64-bit Office (say since Excel 2013...)?
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +We have a web add-in as well, which is backed/interacts with a server, but we are not yet in a position to completely switch away from COM; we use 3rd party DLLs, which are getting harder and harder
```suggestion
We have a web add-in as well, which is backed/interacts with a server, but we are not yet in a position to completely switch away from COM. We use 3rd party DLLs, which are getting harder and harder to come by in 32-bit format.**
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +The Office Add-ins platform team engages at the following locations.
This section should include the channel full name as an anchor to a hot link.

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +    * Documentation - [Word JavaScript API online-only requirement set](https://docs.microsoft.com/javascript/api/requirement-sets/word/word-api-online-requirement-set)
```suggestion
    * Documentation - [Word JavaScript API online-only requirement set](https://docs.microsoft.com/javascript/api/requirement-sets/word/word-api-online-requirement-set)
```
I think you can delete "Documentation - " in front of the link, it's repetitive and unnecessary. Consider removing instances in this section. You can leave "verification form" but I'd move to after the link.

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +    * Verification form - [REST API Add-in verification request](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRxxP2zxSbypLp5NxVTGn_ONUN0JVQ1Y5NlVEUUU4Uk5DSkVYR01KVElVVC4u)
```suggestion
    * [REST API Add-in verification request](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRxxP2zxSbypLp5NxVTGn_ONUN0JVQ1Y5NlVEUUU4Uk5DSkVYR01KVElVVC4u) verification form
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Microsoft 365 Platform Community on [YouTube](https://aka.ms/m365/videos)
```suggestion
* [Microsoft 365 Platform Community on YouTube](https://aka.ms/m365/videos)
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* All Microsoft Developer Community calls(https://aka.ms/M365DevCalls>)
```suggestion
* Invites to all [Microsoft 365 Developer Community calls](https://aka.ms/M365DevCalls)
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Next community call – August 10th at 8:00 AM PT – <https://aka.ms/officeaddinscommunitycall>
```suggestion
* [Join us for our next community call](https://aka.ms/officeaddinscommunitycall) on August 10th at 8:00 AM PT
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Submit questions about add-ins development for our [next community call](https://aka.ms/officeaddinsform)
```suggestion
* [Submit questions about Office Add-ins development](https://aka.ms/officeaddinsform) for our next community call
```

2022-08-10 20:35 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-07-13/index.md
> +* Follow us on [Twitter](https://twitter.com/microsoft365dev)
```suggestion
* [Follow @microsoft365dev on Twitter](https://twitter.com/microsoft365dev)
```

2022-08-19 17:36 UTC, merged