Added CLI for M365 v5.5 release blog post
pnp/blog pull request #472
Opened 2022-07-27 18:32 UTC by Adam-it

## 🏷Category

- [ ] Content fix
- [x] New article

## 👀Contents of the Pull Request

The aim of this PR is to prepare the v5.5 blog release post article in advance so we may make a quicker and smoother release in the coming days

👉[link to nicer view of the blog post](https://github.com/Adam-it/blog/blob/1dd9b616baaca3af419175a43c27d51d046b1ec1/content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md) to improve review experience

2022-07-27 18:33 UTC, Adam-it commented
@garrytrinder ready ✔
Please double review 🙏

2022-07-28 06:48 UTC, LuiseFreese commented
just a reminder that you set the **type** of the previous release post 5.4 to `regular` - thank you 🙏

2022-07-28 06:54 UTC, Adam-it commented
> just a reminder that you set the **type** of the previous release post 5.4 to `regular` - thank you 🙏

I totally forgot about that one 😱.
Thanks for the reminder. Will do 👍

2022-07-28 07:15 UTC, Adam-it commented
> just a reminder that you set the **type** of the previous release post 5.4 to `regular` - thank you 🙏

✔done

2022-07-28 10:08 UTC, garrytrinder requested changes
Just a few minor suggestions, great work @Adam-it 👏

2022-07-28 10:25 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Many organizations use Microsoft Planner to keep track of their work. As you start working with Planner at scale, you'll be likely to need to automate managing plans, buckets and tasks. In this relea
👍✔

2022-07-28 10:25 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Create group with title and description
👍✔

2022-07-28 10:26 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +For more information see the [spo roledefinition get](https://pnp.github.io/cli-microsoft365/cmd/spo/roledefinition/roledefinition-get/), [spo group set](https://pnp.github.io/cli-microsoft365/cmd/sp
👍✔

2022-07-28 10:36 UTC, garrytrinder commented
Just noticed that we should highlight that a new sample was added `listing external users in site groups across all site collections` and that you can now use `@meId` and `@meUsername` tokens in command options.

2022-07-28 11:25 UTC, Adam-it commented
> Just noticed that we should highlight that a new sample was added `listing external users in site groups across all site collections` and that you can now use `@meId` and `@meUsername` tokens in command options.

done ✔

2022-07-28 11:46 UTC, garrytrinder requested changes
A few more updates needed, nearly there 😊

2022-07-28 11:46 UTC, garrytrinder commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Martin Lingstuyl contributed a sample that shows external users in site groups across all site collections [List all external users in site groups across all site collections](https://pnp.github.io/c
Lets include the section heading and description for new scripts.

```suggestion
For more information see the [@meId and @meUserName tokens](https://pnp.github.io/cli-microsoft365/user-guide/using-cli/#meid-and-meusername-tokens)

## New script samples

CLI for Microsoft 365 is a great tool both for quick adjustments to the configuration of your Microsoft 365 tenant as well as automating more complex tasks. Because CLI for Microsoft 365 is cross-platform you can use it on any OS and in any shell. To help you get started using the CLI for Microsoft 365 for automation scenarios, we started gathering some [sample scripts](https://pnp.github.io/cli-microsoft365/sample-scripts/).
 
If you have any scripts that you use frequently, please [share](https://github.com/pnp/cli-microsoft365/discussions) them with us so that we can learn more about the common automation scenarios.

### List all external users in site groups across all site collections

Martin Lingstuyl contributed a sample that shows external users in site groups across all site collections [List all external users in site groups across all site collections](https://pnp.github.io/cli-microsoft365/sample-scripts/spo/list-externalusers-in-sitegroups/).
```

2022-07-28 11:46 UTC, garrytrinder commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Get information about the currently logged user using the Id token
Looks like a typo here

```suggestion
Get information about the currently logged in user using the Id token
```

2022-07-28 11:46 UTC, garrytrinder commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [fonbrauzen](https://github.com/fonbrauzen)
These names are not listed as contributors in the package.json

2022-07-28 11:46 UTC, garrytrinder commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [Jörg Dähler](https://github.com/jdaehler)
This name is not listed as a contributor in the package.json

2022-07-28 11:46 UTC, garrytrinder commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [Konrad K.](https://github.com/wilecoyotegenius)
This name is not listed as a contributor in the package.json

2022-07-28 11:46 UTC, garrytrinder commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [Peter Reavy](https://github.com/preavy)
This name is not listed as a contributor in the package.json

2022-07-28 11:55 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Get information about the currently logged user using the Id token
I think the same typo is also in the spec then 😉

2022-07-28 11:58 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [Peter Reavy](https://github.com/preavy)
👍✔

2022-07-28 11:58 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [Konrad K.](https://github.com/wilecoyotegenius)
👍✔

2022-07-28 11:58 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [Jörg Dähler](https://github.com/jdaehler)
👍✔

2022-07-28 11:58 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +- [fonbrauzen](https://github.com/fonbrauzen)
👍✔

2022-07-28 11:58 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Get information about the currently logged user using the Id token
👍✔

2022-07-28 11:58 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-5/index.md
> +Martin Lingstuyl contributed a sample that shows external users in site groups across all site collections [List all external users in site groups across all site collections](https://pnp.github.io/c
👍✔

2022-07-28 12:04 UTC, garrytrinder approved these changes
All good, great work @Adam-it 🚀

2022-07-28 12:16 UTC, merged