Added new CLI v5.7 beta release blog post
pnp/blog pull request #525
Opened 2022-08-23 01:44 UTC by Adam-it

## Category

- [ ] Content fix
- [X] New article

## Contents of the Pull Request

This is a blog post with our monthly CLI for M365 release sum up.
Currently in draft to make it ready in advance for the upcoming release.

2022-08-24 15:04 UTC, waldekmastykarz requested changes
Very very nice! Let's do a couple adjustments before we release

2022-08-24 15:04 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +There is no better place to find what you are looking for than Microsoft Search. Now we allow the administrator to remove a specific external connection.
Maybe add an extra sentence, that we're continuously extending support for Microsoft Search. Otherwise it feels like there's a gap between the two sentences.

2022-08-24 17:03 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +### What else
sure.. probably there will be a bit more as maybe we will manage to merge something more before the release

2022-08-24 19:50 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +## Contributors
sure. lets double check it just before the release as maybe we may still merge something awesome 🤩

2022-08-25 18:09 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +## Contributors
@waldekmastykarz how is it possible on you list I don't have https://github.com/kevmcdonk ?
I guess he is the author of this PR -> https://github.com/pnp/cli-microsoft365/issues/3170 which is part of 5.7 release

2022-08-25 18:10 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +## Contributors
also https://github.com/Yvand is author of this change 
https://github.com/pnp/cli-microsoft365/issues/2563

2022-08-25 18:33 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +## Contributors
aaa no wait.. I just noticed those are just issues not PR's .. aaaj ok your right.. I will update the list 👍

2022-08-25 18:53 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +We've just published a new major version of the CLI for Microsoft 365 with new commands for working with and managing Microsoft 365 and SharePoint Framework projects on any platform.
done ✅

2022-08-25 18:53 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +### What else
done ✅

2022-08-25 18:53 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +## Contributors
done ✅

2022-08-25 18:53 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +There is no better place to find what you are looking for than Microsoft Search. Now we allow the administrator to remove a specific external connection.
done ✅

2022-08-29 07:27 UTC, waldekmastykarz approved these changes

2022-08-29 07:27 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +For more information see the [business list](https://pnp.github.io/cli-microsoft365/cmd/booking/business/business-list/) and [business get](https://pnp.github.io/cli-microsoft365/cmd/booking/business
```suggestion
For more information see the [business list](https://pnp.github.io/cli-microsoft365/cmd/booking/business/business-list/) and [business get](https://pnp.github.io/cli-microsoft365/cmd/booking/business/business-get/) commands.
```

2022-08-29 07:27 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +For more information see the [spo list roleassignment add](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-roleassignment-add/), [spo list roleassignment remove](https://pnp.github.io/cli-mi
```suggestion
For more information see the [spo list roleassignment add](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-roleassignment-add/), [spo list roleassignment remove](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-roleassignment-remove/) and [spo web roleinheritance reset](https://pnp.github.io/cli-microsoft365/cmd/spo/web/web-roleinheritance-reset/) commands.
```

2022-08-29 07:27 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md
> +For more information see the [search externalconnection remove](https://pnp.github.io/cli-microsoft365/cmd/search/externalconnection/externalconnection-remove/)
```suggestion
For more information see the [search externalconnection remove](https://pnp.github.io/cli-microsoft365/cmd/search/externalconnection/externalconnection-remove/) command.
```

2022-08-29 07:28 UTC, merged