Added 'CLI for Microsoft 365 v5.8' release announcement
pnp/blog pull request #599
Opened 2022-09-26 22:08 UTC by martinlingstuyl

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

This PR contains the release announcement of the v5.8 release of the CLI for Microsoft 365.

2022-09-26 22:54 UTC, Adam-it reviewed
good job @martinlingstuyl  💪
small comments from my side. 
also I would keep the PR in draft for now not to be merged by mistake to fast before we actually do the release 😜

2022-09-26 22:54 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +type: popular
please do remember to change the previous one (5.7) type to `regular`
https://github.com/pnp/blog/blob/main/content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md

2022-09-26 22:54 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +The CLI for Microsoft 365 covers a lot of workloads and functionality. But what if you run into a situation where you need that specific functionality that's not available yet? Of what if you want to
```suggestion
The CLI for Microsoft 365 covers a lot of workloads and functionality. But what if you run into a situation where you need that specific functionality that's not available yet? Or what if you want to leverage your extensive knowledge of API's and call specific endpoints in your scripts. You can now use the new `request` command to do just that. Authentication and web request specifics like throttling and compression are taken care of for you. Adding things like headers and body is super easy. 
```

'Or' instead of 'Of' I guess 🤔

2022-09-26 22:54 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
what about this commit 
https://github.com/pnp/cli-microsoft365/commit/5a588b8bfdda63e50d2c4324de29dd15f4b62c36
with the user: https://github.com/berot3
Should we add him to the list as well 🤔?

2022-09-26 22:54 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### What else
shouldn't we mention also new command added for OneNote 🤔?

2022-09-27 05:07 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +- [Waldek Mastykarz](https://github.com/waldekmastykarz)
Sharp! I must have missed him

2022-09-27 05:11 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### What else
Well, I'm not mentioning everything, that's true, I made a selection.

2022-09-27 07:42 UTC, martinlingstuyl commented
Fixed everything except adding OneNote. If you all think I should add it I will.

2022-09-27 07:59 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### What else
TBH it's always hard to say what functionality might be interesting for the end user 🤔. 
Like with samples: sometimes a very advance sample that does really cool setup may be over sophisticated for someone who is just looking for a simpler case to get started with the tool and check some good practices 😊. In my opinion it's really hard to actually decide what brings actual value  to someone else 👍.
If we have some additional time before the release maybe we could add also some small information about this command? I guess if someone will not be interested in it she or he may just skip this chapter 😊. But I think it's better if the reader decides not the filter 😉
What's your opinion on that?

2022-09-27 08:05 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### What else
In a general sense I agree with you. I just left it out as a matter of selection. It would not make sense to write 'These features are just the tip of the ice berg' if you actually write about the entire iceberg 😁
But apparently you feel strongly about including this command in the release announcement, that's okay, I'll add a short piece.

2022-09-27 08:17 UTC, martinlingstuyl commented
I've added a section about OneNote as well @Adam-it 🤙

2022-09-27 08:41 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### What else
I guess we don't include every change usually just the new or the big once 😉. 
thanks for the additional effort 👍. You rock 🤩🤩

2022-09-27 09:04 UTC, Jwaegebaert reviewed
Wonderful job @martinlingstuyl!!

I've a few pointers that could help out 😄

2022-09-27 09:12 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +The CLI for Microsoft 365 covers a lot of workloads and functionality. But what if you run into a situation where you need that specific functionality that's not available yet? Or what if you want to
Never knew :)

2022-09-27 09:14 UTC, martinlingstuyl commented
> Wonderful job @martinlingstuyl!!
> 
> I've a few pointers that could help out 😄

Fixed!

2022-09-27 18:24 UTC, martinlingstuyl commented
Could you guys approve this one @Jwaegebaert, @Adam-it ?

2022-09-27 18:36 UTC, Jwaegebaert approved these changes

2022-09-27 18:36 UTC, Jwaegebaert commented
Check, ready to go 🚀

2022-09-27 19:44 UTC, waldekmastykarz requested changes
Very nice! Awesome call out for hacktoberfest! 👏

2022-09-27 19:44 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### Manage SharePoint Online permissions and updating Content Types
Let's split this into two separate sections for readability

2022-09-27 19:44 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### Manage SharePoint Online permissions and updating Content Types
No need to capitalize _content type_

2022-09-27 19:44 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### Retrieving Microsoft Graph insights
Since insights is a specific endpoint on Microsoft Graph, let's not use this word here and use change log instead as that's what we're retrieving

2022-09-27 19:44 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-8/index.md
> +### Listing OneNote Notebooks
Let's not capitalize _notebooks_ to make it consistent with the content below

2022-09-27 20:13 UTC, Adam-it approved these changes
look at me, approving a blog post 😉. Those are strange times we live in 🙂

2022-09-27 20:14 UTC, Adam-it commented
> Could you guys approve this one @Jwaegebaert, @Adam-it ?

approved ✅
sorry for the hold up
awesome work  BTW👍

2022-09-29 07:59 UTC, LuiseFreese commented
I will leave these CLI posts to the CLI crew, oki??

2022-09-29 08:23 UTC, martinlingstuyl commented
> I will leave these CLI posts to the CLI crew, oki??

Approval, yes, Merging the PR cannot be done by me though.

2022-09-29 10:47 UTC, LuiseFreese commented
apparently @waldekmastykarz requested a change that is still not addressed. Happy to assist with merging, but Waldek can do this as well after he checked the requested changes :-)

2022-09-30 09:00 UTC, merged