Added 'CLI for Microsoft 365 v5.9' release announcement
pnp/blog pull request #668
Opened 2022-10-27 10:14 UTC by Jwaegebaert

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

This PR is the release announcement for the v5.9 release of the CLI for Microsoft 365.
Currently in draft to make it ready in advance for the upcoming release.

2022-10-27 10:14 UTC, Jwaegebaert commented
@pnp/cli-for-microsoft-365-maintainers could you take a look at the content

2022-10-27 11:38 UTC, waldekmastykarz requested changes
Awesome! Let's do a few small changes

2022-10-27 11:38 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +Just started playing around with the preview of Power Apps cards and you want to do some more automation? No worries, CLI for Microsoft 365 got you covered. We stay up to date with the latest tools a
`...has got you covered...`

2022-10-27 11:38 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +### Manage **MORE** SharePoint Online permissions
```suggestion
### Improved managing permissions in SharePoint Online
```

2022-10-27 11:38 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +
Let's also mention the new ability to send emails with attachments that we've added in this release

2022-10-27 11:38 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +Check out the [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v580) for the complete list of what's new and improved.
We should link to v5.9.0 here

2022-10-27 11:38 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +### New contributors
Awesome idea to call out new contributors! 👏

2022-10-27 18:13 UTC, milanholemans requested changes
The pen is mightier than the sword, that's for sure! @Jwaegebaert proved just that by writing this post. 😉 

I made some remarks on what I'd change. You can decide for yourself which one you want to take over and which not.

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +Check out the [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v590) for the complete list of what's new and improved.
Personally, I find we direct the user a lot of times to the release notes 😄
Although it's fine in this place here.

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +A warm welcome to all our new contributors! (in alphabetical order):
```suggestion
A warm welcome to this month's new contributors! (in alphabetical order):
```

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +We're actively working on improving our documentation and adding response output to all our commands. This is a lot of work because we have a ton of commands. A few commands are already done to show
```suggestion
We're actively working on improving our documentation and adding response output to all our commands. This is a lot of work because we have a ton of commands. A few commands are already done to show an example of what we are trying to do, but we are definitely looking for contributors to help us. If you feel like writing some documentation be sure to take a look at [this issue](https://github.com/pnp/cli-microsoft365/issues/3754).
```

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +
Maybe we should also mention that we are adding some more Power Platform commands as well 😊

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +If you need more help getting started or want more details about the commands, architecture, or project, go to [aka.ms/cli-m365](https://aka.ms/cli-m365). And if you see any room for improvement, ple
```suggestion
If you need more help getting started or want more details about the commands, architecture, or project, go to [aka.ms/cli-m365](https://aka.ms/cli-m365). If you see any room for improvement, please, don't hesitate to reach out to us either on [GitHub](https://github.com/pnp/cli-microsoft365/discussions), [Discord](https://discord.com/invite/7rfW4kg6B5), or [Twitter](https://twitter.com/climicrosoft365).
```

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +date: 2022-10-31T22:00:00.000Z
Blog will be posted during the day isn't it? 😄 
No idea how important this date is, maybe change it to 12:00 😄

2022-10-27 18:13 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +Hacktoberfest was a great success! Thanks so much to all our active and new contributors for your hard work and to all the maintainers for creating so many good first issues.
Thanks so much is informal English.

```suggestion
Hacktoberfest was a great success! Thank you so much to all our active and new contributors for your hard work and to all the maintainers for creating so many good first issues. 
```

2022-10-28 08:51 UTC, Adam-it reviewed
@Jwaegebaert  awesome blog post 💪
you rock 🤩 as always. 
just small comment from my side 😉
thanks for your awesome work 👍

2022-10-28 08:51 UTC, Adam-it commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +CLI for Microsoft 365 is constantly growing and evolving. We're always looking for ways to improve. There are still many areas not covered by the CLI as well as many amazing ideas for unique features
TBH I would remove the information about discussion on 
- manage file versioning - this we agreed we will do and I already created a issue for group of commands and will now create issues for each command as soon as I find time to do it 😉
- the document set discussion is dead ☠ - and not many folks care about this functionality so lets not focus on it now 😉

2022-10-28 09:31 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v5-9/index.md
> +date: 2022-10-31T22:00:00.000Z
This date can't be in the future because otherwise it will publish the post as draft. Ideally, it should be set on the day when the article goes live, ie. Oct 31.

2022-10-28 09:44 UTC, Jwaegebaert commented
Great work everyone! All the suggestions have been applied.

2022-10-31 07:42 UTC, waldekmastykarz approved these changes

2022-10-31 07:42 UTC, merged