November 9th Community Call Blog Post
pnp/blog pull request #729
Opened 2022-11-16 19:01 UTC by preethikakiru

[X] New article
This pull request is trying to merge changes to post the November 9th Office Add-ins Community Call blog post.
Just as a note, still need to add a few more questions and answers to the Q&A portion, but still waiting on answers from the respective SMEs.

2022-11-16 20:18 UTC, davidchesnut requested changes
Looks good, a few comments added for your review.

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +summary: "This month's community call topics include: Update the ASP.NET server in Visual Studio (update a task pane in an Excel add-in updating the sideloader project to point to an updated ASP.NET
This is the October summary.

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* Please complete the [Office add-in developing experience survey](https://forms.office.com/r/wmzCgccbPa)
This link goes to a 2021 form. Is this the correct link?

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* **Working with Partial Documents in PowerPoint.** Pertains to large files laden with graphics and videos are broken up for faster downloading.  What and why Partial docs? Capabilities explained, im
This asks for feedback. Is there a link or info on how folks can do that?

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +This is one of the things we are considering. We would love to hear more of your use case via aka.ms/WordAPI.
```suggestion
This is one of the things we are considering. We would love to hear more of your use case via https://aka.ms/WordAPI.
```

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +We're sorry to hear you're experiencing challenges with developing your Outlook add-in. If you haven't already, please submit a GitHub issue, so that we can assist you.
```suggestion
We're sorry to hear you're experiencing challenges with developing your Outlook add-in. If you haven't already, please submit a [GitHub issue](https://github.com/OfficeDev/office-js/issues), so that we can assist you.
```

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +We usually debug SSO issues with the browser dev tools. If you haven't already, please submit a GitHub issue, so that we can assist you further.
```suggestion
We usually debug SSO issues with the browser dev tools. If you haven't already, please submit a [GitHub issue](https://github.com/OfficeDev/office-js/issues), so that we can assist you further.
```

2022-11-16 20:18 UTC, davidchesnut commented on content/office-add-ins-community-call/2022-11-09/index.md
> +If you're experiencing issues with developing an Excel add-in, please submit a GitHub issue, so that we can assist you further.
```suggestion
If you're experiencing issues with developing an Excel add-in, please submit a [GitHub issue](https://github.com/OfficeDev/office-js/issues), so that we can assist you further.
```

2022-11-16 23:13 UTC, lindalu-MSFT requested changes
Please review my edits to the call summary descriptions!

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* **Content control enhancements in Word Online.** Content controls are being enhanced – what’s new and in the works. Content controls in Word (supported types since 2013 and creating via UI and prog
```suggestion
* **Content control enhancements in Word Online.** This presentation covers new and upcoming enhancements to content controls in Word including those created via UI and programmatically (Word for Windows) and those created with Rich Text in Office.js (Word Online). What’s new and in the pipeline.  
```

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* **Search Bar for Office Add-ins.** Helping users find their add-ins. Users can search for installed add-ins from the search box (TellMe) on the top of the Word, Excel and PowerPoint documents. Supp
```suggestion
* **Search Bar for Office Add-ins.** Learn how users can use TellMe to search for installed add-ins from the search box in Word, Excel and PowerPoint documents. Supports user installed add-ins and admin deployed add-ins. 
```
Please feel free to edit if I cut too much!

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +**We'd also love an update on https://github.com/OfficeDev/office-js/issues/2955 - Outlook OWA UI has been updated for some users and there is no way for them to open add-ins in compose mode. Major i
```suggestion
**We'd love an update on [GitHub issue](https://github.com/OfficeDev/office-js/issues/2955): Outlook OWA UI has been updated for some users and there is no way for them to open add-ins in compose mode. Major issue.**
```

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +**Hi, anyone working on Outlook add-in - SSO with .Net Core - adding Authentication in Middleware. and adding redirect URI? This works in Outlook windows app but fails in Outlook from browser.**
```suggestion
**Hi, anyone working on Outlook add-in - SSO with .NET Core - adding Authentication in Middleware and adding redirect URI? This works in Outlook on Windows but fails in Outlook on the web.**
```

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +**Any one working on Excel add in pivot table function and connect with external data source mainly cube in pivot table inside add-in?**
```suggestion
**Any one working on Excel add-in pivot table function and connect with external data source mainly cube in pivot table inside add-in?**
```

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +Support for PlainText content controls editing will  roll out soon.
```suggestion
We are planning to roll out support for Plain Text content controls editing soon.
```

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +**How do you match the office add-in to the user search phrase in the new search functionality?**
```suggestion
**How do you match the Office Add-in to the user search phrase in the new search functionality?**
```

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +**Would the search work only by the add-in name, or use some additional descriptions?**
Consider merging this with the previous question since the answer is identical.

2022-11-16 23:13 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* **Working with Partial Documents in PowerPoint**
```suggestion
* **Working with partial documents in PowerPoint**
```

2022-11-17 17:38 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-11-09/index.md
> +summary: "This month's community call topics include: Update the ASP.NET server in Visual Studio (update a task pane in an Excel add-in updating the sideloader project to point to an updated ASP.NET
That's totally my bad I did not realize I didn't update that. Thank you for pointing that out!

2022-11-17 17:40 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* **Working with Partial Documents in PowerPoint.** Pertains to large files laden with graphics and videos are broken up for faster downloading.  What and why Partial docs? Capabilities explained, im
I didn't get any form from John or Onur

2022-11-17 17:48 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* **Working with Partial Documents in PowerPoint.** Pertains to large files laden with graphics and videos are broken up for faster downloading.  What and why Partial docs? Capabilities explained, im
I think they were just asking for feedback from the audience of the community call so I will remove that line for the blog post.

2022-11-17 17:49 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* Please complete the [Office add-in developing experience survey](https://forms.office.com/r/wmzCgccbPa)
which link are you referring too?

2022-11-17 18:53 UTC, davidchesnut approved these changes
Looks good!

2022-11-17 18:54 UTC, preethikakiru commented on content/office-add-ins-community-call/2022-11-09/index.md
> +* Please complete the [Office add-in developing experience survey](https://forms.office.com/r/wmzCgccbPa)
hmm ok, I think I'm going to go ahead and delete this survey for now. Cause it seems to have been something for the December 2021 community call

2022-11-17 21:38 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +summary: "This month's community call topics include Working with Partial Documents in PowerPoint (Large files are broken up for faster downloading) by John Teichman - Principal Product Manager(Micro
```suggestion
summary: "This month's community call topics include Working with Partial Documents in PowerPoint (Large files are broken up for faster downloading) by John Teichman - Principal Product Manager (Microsoft) and Onur Onder - Senior Software Engineer (Microsoft), Content control enhancements in Word Online (what’s new and in the works) by Maja Damjanić - Senior Product Manager (Microsoft) and Search Bar for Office Add-ins (Help users find their add-ins) by Adrian Wu: Senior Product Manager (Microsoft), and Q&A at end of call and in chat throughout call. The call was hosted by Preethika Kiruveedula (Microsoft)."
```

2022-11-17 21:38 UTC, lindalu-MSFT commented on content/office-add-ins-community-call/2022-11-09/index.md
> +summary: "This month's community call topics include Working with Partial Documents in PowerPoint (Large files are broken up for faster downloading) by John Teichman - Principal Product Manager(Micro
As this is metadata and used in SERP, I think we should shorten it so it fits in the search results and has better SEO.

2022-11-17 21:42 UTC, lindalu-MSFT approved these changes
Approve but suggestion for call summary metadata blurb! Otherwise, looks awesome. Thanks for including me!

2022-11-17 22:05 UTC, preethikakiru commented
@lindalu-MSFT Thanks for reviewing so quickly!

2022-11-17 22:05 UTC, merged