Adds CLI for Microsoft 365 v6.1 release article
pnp/blog pull request #836
Opened 2022-12-27 01:48 UTC by Adam-it

## Category

- [X] New article

## Contents of the Pull Request

This PR adds a new release article of CLI for Microsoft v6.1 beta

2022-12-27 01:49 UTC, Adam-it commented
@pnp/cli-for-microsoft-365-maintainers please do double check 🙏.

2022-12-27 08:20 UTC, waldekmastykarz requested changes
Awesome! Let's do a few adjustments 👏

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +m365 pp dataverse table row list -environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --name "Appointment"
```suggestion
m365 pp dataverse table row list --environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --name "Appointment"
```

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +m365 pp dataverse table row remove -environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --name "Appointment" --id 3
```suggestion
m365 pp dataverse table row remove --environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --name "Appointment" --id 3
```

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To learn more about managing Power Platform Dataverse tables rows, publishers and chatbot, see the [m365 pp chatbot get](https://pnp.github.io/cli-microsoft365/cmd/pp/chatbot/chatbot-get/), [m365 pp
Let's simplify this by pointing to the first command of the series and let readers find out the rest when they're in the docs.

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To delete a retention label by id simply:
```suggestion
To delete a retention label by id, execute:
```

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To update a retention label so that it retains documents as records and deletes them after one year.
```suggestion
To update a retention label, so that it retains documents as records and deletes them after one year, run:
```

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To learn more about managing r etention labels commands, see the [m365 purview retentionlabel list](https://pnp.github.io/cli-microsoft365/cmd/purview/retentionlabel/retentionlabel-list/), [m365 purv
Let's simplify this by naming just the first command in the series.

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To learn more about managing r etention labels commands, see the [m365 purview retentionlabel list](https://pnp.github.io/cli-microsoft365/cmd/purview/retentionlabel/retentionlabel-list/), [m365 purv
Typo in `r etention`

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +Check out the [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v610-beta) for the complete list of what's new and improved.
```suggestion
Check out the [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v610) for the complete list of what's new and improved.
```

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +If you use CLI a lot, you might find it tedious to have to repeat some options like the URL of the site or a list you want to work with.
```suggestion
If you use the CLI a lot, you might find it tedious to have to repeat some options like the URL of the site or a list you want to work with.
```

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +- [Mathijs Verbeeck](https://github.com/MathijsVerbeeck)
Since we listed all these folks among contributors, let's remove them here to avoid repetition.

2022-12-27 08:20 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +- [Mathijs Verbeeck](https://github.com/MathijsVerbeeck)
Shall we add:

- dojcsakj: https://github.com/pnp/cli-microsoft365/issues/4256
- JJFranko: https://github.com/pnp/cli-microsoft365/issues/4225
- [Jussi Palo](https://github.com/jpalo) https://github.com/pnp/cli-microsoft365/issues/4208

In all cases, their feedback led to some improvements that we did in the CLI.

2022-12-27 15:36 UTC, milanholemans requested changes
Great job @Adam-it!

2022-12-27 15:36 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +m365 pp dataverse table row list -environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --name "Appointment"
```suggestion
m365 pp dataverse table row list -environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --tableName "Appointment"
```

2022-12-27 15:36 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +m365 pp dataverse table row remove -environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --name "Appointment" --id 3
```suggestion
m365 pp dataverse table row remove -environment  "Default-2ca3eaa5-140f-4175-8261-3272edf9f339" --tableName "Appointment" --id 3
```

2022-12-27 15:36 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +
Personally what I also find useful is that people can get their default pp environment more easily now using `m365 pp environment get` https://github.com/pnp/cli-microsoft365/issues/4228

Maybe we can also tell about our new telemetry page (https://pnp.github.io/cli-microsoft365/about/telemetry)? Or nah?

2022-12-27 16:26 UTC, Jwaegebaert approved these changes
Great job @Adam-it. I've left a few suggestions for possible typo fixes 😄

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +### More Power Platfrom commands
```suggestion
### More Power Platform commands
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +### More Power Platfrom commands
```suggestion
### More Power Platform commands
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To get chatbot with given id in the default environment you may run:
```suggestion
To get a chatbot with a given id in the default environment you may run:
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To remove chatbot with given ID in the default environment and prompt for confirmation simply run:
```suggestion
To remove the chatbot with the given ID in the default environment and prompt for confirmation simply run:
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To add publisher in the environment using the name and the prefix simply run:
```suggestion
To add a publisher in the environment using the name and the prefix simply run:
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +In order to get a list of retention labels run:
```suggestion
To get a list of retention labels run: 
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +In order to simplify using commands with boolean options we refactored the way we handle them. Now you can use the following values to specify boolean options:
```suggestion
To simplify using commands with boolean options we refactored the way we handle them. Now you can use the following values to specify boolean options: 
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +For true you may use: `1`, `yes`, `true`, `on` and for false: `0`, `no`, `false`, `off`
```suggestion
For true you may use: `1`, `yes`, `true`, `on`, and for false: `0`, `no`, `false`, `off`
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +These features are just the tip of the ice berg of what we've shipped in this version. The code base of the CLI for Microsoft 365 has received a huge update as well, making it easier for maintainers
```suggestion
These features are just the tip of the iceberg of what we've shipped in this version. The code base of the CLI for Microsoft 365 has received a huge update as well, making it easier for maintainers and contributors to create new functionality. And so many other fixes.
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +#### Manage application customizer and commandset extensions
```suggestion
#### Manage application customizers and command set extensions
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To some extend CLI for Microsoft 365 already supports managing application customizers and commandset extensions. In order to make this even easier we are currently working on ways to improve the exp
```suggestion
To some extent, CLI for Microsoft 365 already supports managing application customizers and command set extensions. To make this even easier we are currently working on ways to improve the experience with additional commands and adding support to manage tenant-wide extensions. If you are interested to read more about what we are planning, see the [related issue](https://github.com/pnp/cli-microsoft365/issues/4219).
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To some extend CLI for Microsoft 365 already supports managing application customizers and commandset extensions. In order to make this even easier we are currently working on ways to improve the exp
```suggestion
To some extent, CLI for Microsoft 365 already supports managing application customizers and command set extensions. To make this even easier we are currently working on ways to improve the experience with additional commands and adding support to manage tenant-wide extensions. If you are interested to read more about what we are planning, see the [related issue](https://github.com/pnp/cli-microsoft365/issues/4219).
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To help you save time, we're working on adding the concept of context to CLI for Microsoft 365. Using the context, you will be able to store in a file default values for specific options. When you ru
```suggestion
To help you save time, we're working on adding the concept of context to CLI for Microsoft 365. Using the context, you will be able to store in a file default values for specific options. When you run a command that has a context value defined, and you haven't specified the option explicitly yourself, CLI for Microsoft 365 will automatically use the value from the context saving you some work and typing! For more information about what we've got planned, see the [related issue](https://github.com/pnp/cli-microsoft365/issues/3896).
```

2022-12-27 16:26 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To help you save time, we're working on adding the concept of context to CLI for Microsoft 365. Using the context, you will be able to store in a file default values for specific options. When you ru
```suggestion
To help you save time, we're working on adding the concept of context to CLI for Microsoft 365. Using the context, you will be able to store in a file default values for specific options. When you run a command that has a context value defined, and you haven't specified the option explicitly yourself, CLI for Microsoft 365 will automatically use the value from the context saving you some work and typing! For more information about what we've got planned, see the [related issue](https://github.com/pnp/cli-microsoft365/issues/3896).
```

2022-12-28 10:13 UTC, martinlingstuyl requested changes

2022-12-28 10:13 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To learn more about managing r etention labels commands, see the [m365 purview retentionlabel list](https://pnp.github.io/cli-microsoft365/cmd/purview/retentionlabel/retentionlabel-list/), [m365 purv
Aside from introducing CRUD commands for purview retention labels, we've also added the possibility to list the available (published) retention labels on a specific SharePoint site and the possibility to clear the retention label on a list item.

https://pnp.github.io/cli-microsoft365/cmd/spo/web/web-retentionlabel-list/
(This is different from listing all available purview retention labels)

https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-retentionlabel-remove/

2022-12-28 10:13 UTC, martinlingstuyl commented
Also one comment from me on retention labels. Great work Adam!

2022-12-28 10:43 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md
> +To learn more about managing r etention labels commands, see the [m365 purview retentionlabel list](https://pnp.github.io/cli-microsoft365/cmd/purview/retentionlabel/retentionlabel-list/), [m365 purv
So the difference is we've added commands to manage them and commands to use them on SharePoint

2022-12-30 22:10 UTC, Adam-it commented
thanks @waldekmastykarz , @Jwaegebaert , @milanholemans , @martinlingstuyl  for your great reviews 👍
I resolved your comments. It seems to me to be more or less ready 😉

2022-12-31 09:11 UTC, waldekmastykarz approved these changes

2022-12-31 09:11 UTC, merged