Cli for M365 release post v6.2
pnp/blog pull request #960
Opened 2023-01-24 23:01 UTC by milanholemans

## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

Release post of CLI for Microsoft 365 version `6.2`

2023-01-26 08:58 UTC, waldekmastykarz requested changes
Awesome! 👏

2023-01-26 08:58 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Eureka! Finally we can use application permissions for Planner commands. This much requested feature is currently rolling out preview. Previously we showed a friendly error that told that application
_is currently rolling out **in** preview_

2023-01-26 08:58 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +In our previous release we have taken the first steps to create a CLI context. This allows you to save time by storing default values for options that you often use. For example, if you're working wi
Let's clarify that this is the idea, but we don't support context just yet. We allow managing context settings but don't apply them to commands just yet.

2023-01-26 08:58 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +
I suggest we add information about updates to booleans - which significantly simplify using the CLI, and CI/CD guidance to make it easier for folks to use CLI in their deployment pipelines.

2023-01-26 08:58 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +- [Tim Van de Voorde](https://github.com/timdelavoorde)
I haven't seen any PRs from Tim in the git story, or have I missed it?

2023-01-26 10:09 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +- [Tim Van de Voorde](https://github.com/timdelavoorde)
He made a PR https://github.com/pnp/cli-microsoft365/pull/4271, but something went wrong while committing his PR, his name was dropped of the commit. https://github.com/pnp/cli-microsoft365/commit/58ae9e6b56f5f2d38c44e93dbf3d9ca26cdc7a90

2023-01-26 10:29 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +
I saw that this was already included in our previous release post, or do you mean something else?

https://github.com/pnp/blog/blob/6727797d63148f03298f373e8258ed8eb50cbb01/content/cli-for-microsoft-365/cli-for-microsoft-365-v6-1/index.md?plain=1#L147-L151

2023-01-26 11:09 UTC, Jwaegebaert requested changes
Great job @milanholemans! I've left a few comments on some possible typos 😄

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +SharePoint is all about collaborating with people on documents. Previously we introduced some commands to manage permissions on documents. With our new commands you can share your SharePoint files wi
```suggestion
SharePoint is all about collaborating with people on documents. Previously we introduced some commands to manage permissions on documents. With our new commands, you can share your SharePoint files with anyone you like. In this release, we are introducing commands to manage sharing links on documents.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Eureka! Finally we can use application permissions for Planner commands. This much requested feature is currently rolling out in preview. Previously we showed a friendly error that told that applicat
```suggestion
Eureka! Finally, we can use application permissions for Planner commands. This much-requested feature is currently rolling out in preview. Previously we showed a friendly error that told us that application permissions don't work for Planner commands, this check has now been removed. You are now free to experiment with our Planner commands with application permissions! You can do this quickly and easily by just creating a new application registration in Azure AD with Planner application permissions, logging in to the CLI with a [certificate](https://pnp.github.io/cli-microsoft365/user-guide/connecting-office-365/#log-in-using-a-certificate) or [secret](https://pnp.github.io/cli-microsoft365/user-guide/connecting-office-365/#log-in-using-a-secret), and you are good to go!
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +In our previous release we introduced commands to manage compliance within your tenant. This was just the beginning, our v6.2 release contains even more compliance commands.
```suggestion
In our previous release, we introduced commands to manage compliance within your tenant. This was just the beginning, our v6.2 release contains even more compliance commands.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Checkout our [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v620) for more Purview related commands.
```suggestion
Check out our [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v620) for more Purview related commands.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +In our previous release we have taken the first steps to create a CLI context. This allows you to save time by storing default values for options that you often use. For example, if you're working wi
```suggestion
In our previous release, we have taken the first steps to create a CLI context. This allows you to save time by storing default values for options that you often use. For example, if you're working with a specific site collection, you can save the URL of the site collection in the context, and CLI for Microsoft 365 will automatically use it when you run a command that requires the URL of the site collection. This way, you don't have to specify the URL of the site collection every time you run a command. In this release, we created extra commands to work with the CLI context. Note this is still a work in progress. We allow managing context settings but don't apply them to commands just yet.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +In the past releases we gave more focus to our Power Platform commands. This month is not different. Also, in this release we have new Power Platform commands, especially about AI Builder Models.
```suggestion
In the past releases, we gave more focus to our Power Platform commands. This month is no different. Also, in this release, we have new Power Platform commands, especially about AI Builder Models.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Rosters are a new type of container for Microsoft Planner plans. This enables users to create a Planner plan without the need to create a new Microsoft 365 group (with a mailbox, SharePoint site, ...
```suggestion
Rosters are a new type of container for Microsoft Planner plans. This enables users to create a Planner plan without the need to create a new Microsoft 365 group (with a mailbox, SharePoint site, ...). Access to Roster-contained plans is controlled by the members of the Roster. However Planner Rosters are still in preview, we are already working on providing the necessary commands for this.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +With this release you are able to easily manage sharing links for SharePoint files. We don't stop here, we have more commands on our roadmap to manage sharing links. We are planning to create more co
```suggestion
With this release, you are able to easily manage sharing links for SharePoint files. We don't stop here, we have more commands on our roadmap to manage sharing links. We are planning to create more commands to manage sharing links for SharePoint folders, SharePoint list items, OneDrive files, ...
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Currently CLI for Microsoft 365 support few commands for SPFx solutions. In the upcoming weeks we are planning to create more SPFx commands with a focus on SPFx extensions. Planning to add, set, list
```suggestion
Currently, CLI for Microsoft 365 supports a few commands for SPFx solutions. In the upcoming weeks, we are planning to create more SPFx commands with a focus on SPFx extensions. Planning to add, set, list, and remove SPFx extensions such as ListView Command Sets or Application Customizers? We provide everything to make your life easier.
```

2023-01-26 11:09 UTC, Jwaegebaert commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +In our previous release we introduced commands to manage compliance within your tenant. This was just the beginning, our v6.2 release contains even more compliance commands.
Maybe we could provide a bit more insight here regarding all the new commands mentioned here

2023-01-26 12:27 UTC, martinlingstuyl requested changes
Looks good @milanholemans, just a few comments

2023-01-26 12:27 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +To add create a new retention label, run:
To add create?

2023-01-26 12:27 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +To add/set a retention label on a file, run:
We could also use the word ‘apply’ here as that’s what you do: apply a label. Add/set is CLI words

2023-01-26 12:27 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +To remove a retention label from a folder, run:
Use the word clear instead of remove is better

2023-01-26 12:27 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Rosters are a new type of container for Microsoft Planner plans. This enables users to create a Planner plan without the need to create a new Microsoft 365 group (with a mailbox, SharePoint site, ...
Even though planner rosters are still in preview…

2023-01-26 12:27 UTC, martinlingstuyl commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +Check out our [release notes](https://pnp.github.io/cli-microsoft365/about/release-notes/#v620) for more Purview related commands.
Maybe add a small section naming the additional commands would be good…

2023-01-26 18:47 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +
Ah right, seems like in this release we only updated the guidance. Never mind. Carry on.

2023-01-26 18:48 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +- [Tim Van de Voorde](https://github.com/timdelavoorde)
Did we somehow lost him when merging his PR? That's a shame 😞 If it's not too far back, we could see if we could update the PRs author to him to attribute his work to him.

2023-01-26 18:57 UTC, milanholemans commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +- [Tim Van de Voorde](https://github.com/timdelavoorde)
That will require a force push on the main branch right?

2023-01-27 09:24 UTC, waldekmastykarz commented on content/cli-for-microsoft-365/cli-for-microsoft-365-v6-2/index.md
> +- [Tim Van de Voorde](https://github.com/timdelavoorde)
Correct

2023-01-31 07:42 UTC, waldekmastykarz approved these changes

2023-01-31 07:42 UTC, merged